### ISSUE TITLE
Please add Hacktoberfest and GSSoC-EXT tags

### ISSUE THREAD

**Issue by HarshitShukla-dev** [param-code/counter-app#1]
Hi,
Could you please add the Hacktoberfest and GSSoC-EXT tags to the repository? This will help contributors participate in both events.
Thanks!

**Comment by param-code** [comment]
I have added both the tags you have asked for.

**Comment by HarshitShukla-dev** [comment]
Hey @param-code, it looks like you've added the tags to the release, but the changes need to be made in the **Edit Repository** section instead. Specifically, you'll need to add the topics under **Topics**.

Here's how you can do it:

1. Click on the gear icon in the **repository's main page**, as shown in the screenshot below:

   ![Screenshot 2024-10-02 002333](https://github.com/user-attachments/assets/639fa936-8ede-4c03-bc82-cc56291ce81e)

2. In the **Topics** section, add both the relevant topics, as shown here:

   ![Screenshot 2024-10-02 002355](https://github.com/user-attachments/assets/3646036b-28c8-4c57-bdc8-f1ff6461cef6)

Let me know if you need any more help!

**Comment by param-code** [comment]
Thanks!! I have made the changes can you check and verify is it correct? now
