### ISSUE TITLE
Updating README

### ISSUE THREAD

**Issue by param-code** [param-code/counter-app#10]
Go through the Project and update the README adding screenshots and listing the features.Also you may add gif or mini video demonstrating the working.

**Comment by Lonwwolf14** [comment]
I would like to work on this issue will you please assign me this 1

**Comment by kushwxha** [comment]
hey @param-code ,
can you please assign it to me??

**Comment by param-code** [comment]
Yeah Yeah sure!! I am assigning both of you.All the Best!!Will see later which one to merge.
