### ISSUE TITLE
[Feature]: Adding Sign In feature 

### ISSUE THREAD

**Issue by Abhishek2634** [param-code/counter-app#100]
# 🚀 Feature Request

### 📝 Feature Description
i want to add sign in option, currently there is only sign up option present

### 🔧 How Will This Enhance the App?
i will be good if any person is already signup there is no need to signup again

### 📦 Suggested Implementation
i will make changes in the signup page make use of usestate
@sanjay-kv , @param-code   assign this issue to me pls under hacktoberfest label.

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> i want to add sign in option, currently there is only sign up option present
> 
> ### 🔧 How Will This Enhance the App?
> i will be good if any person is already signup there is no need to signup again
> 
> ### 📦 Suggested Implementation
> i will make changes in the signup page make use of usestate @sanjay-kv , @param-code assign this issue to me pls under hacktoberfest label.

okay.Move forward with  your ideas @Abhishek2634 .
