### ISSUE TITLE
[Bug]: Input text not visible for Timer in dark mode

### ISSUE THREAD

**Issue by RchtDshr** [param-code/counter-app#101]
# 🐞 Bug Report

### 📋 Description
Input text not visible for timer section in dark mode which creates a confusion for dark mode users as to where input the time.

### ⚙️ Steps to Reproduce
1. Go to timer page.
2. Switch to dark mode.
3. Type the time in input.

### ✔️ Expected Behavior
The input text should be visible in dark as well as light mode.

### ❌ Actual Behavior
Input text for timer input is not visible.

### 📷 Screenshots
![image](https://github.com/user-attachments/assets/00a1dcf7-a3b3-4615-94c4-5bbf9cb32547)
![image](https://github.com/user-attachments/assets/97d46950-f06c-48a0-a59d-26ad20384fe0)

**Comment by RchtDshr** [comment]
hey @param-code , can i work on this please?

**Comment by param-code** [comment]
> hey @param-code , can i work on this please?

Yes yes.
