### ISSUE TITLE
[Feature]: Add Multilanguage Support

### ISSUE THREAD

**Issue by 17arindam** [param-code/counter-app#102]
# 🚀 Feature Request

### 📝 Feature Description
Add multilanguage support where user can select the language at which they want to view website

### 🔧 How Will This Enhance the App?
This  will enhance app by giving more options to users to view this website

### 🎯 Use Cases
Will increase user interaction of the user

### 📸 Additional Context
![Screenshot 2024-10-11 021737](https://github.com/user-attachments/assets/3c6677cf-5e9f-47f9-b803-5bcf82c21583)

**Comment by 17arindam** [comment]
@param-code please assign me this issue

**Comment by param-code** [comment]
> @param-code please assign me this issue

Yes yes ofcourse.Go ahead with your idea.
