### ISSUE TITLE
[Feature]: Add a Footer across the website

### ISSUE THREAD

**Issue by Someshog** [param-code/counter-app#106]
# 🚀 Feature Request

### 📝 Feature Description
I propose adding a footer section to our website to improve navigation, provide additional information, and enhance the overall user experience. A well-designed footer will be accessible on every page, serving as a valuable resource for users at all times.

#### This will include:
- Contact Information
- Quick Links
- Social Media Icons
- "Made by..." Credit
### 🎯 Use Cases
Users can quickly find essential links and information without having to scroll back to the top, which enhances their browsing experience.
### 📦 Suggested Implementation
- The footer should align with our current branding and design guidelines to maintain consistency.
- Ensure that the footer is mobile-friendly and displays correctly on all devices.

### 📸 Additional Context
N/A

**Comment by NinaVincova** [comment]
Hello :) It is possible to work on this issue? Can it be assigned?

**Comment by param-code** [comment]
Okay.I am assigning this to both of you.All the Best!!
