### ISSUE TITLE
[Bug]: No Placeholder in input tag in signin and signup

### ISSUE THREAD

**Issue by harshbhar0629** [param-code/counter-app#110]
# 🐞 Bug Report

### 📋 Description
When we try to login and create account they show me a form but in form there are some inputs but no input suggest any thing placeholder of every input is missing.

### ⚙️ Steps to Reproduce
1. Go to login page and signup page.
2. Give placeholder to every input.

### ✔️ Expected Behavior
When input have a placeholder so interaction of user is increased!

### ❌ Actual Behavior
In form it shows only input tag no suggestion available

### 📷 Screenshots
![placeholder](https://github.com/user-attachments/assets/ffbad680-5d9b-4f33-afaf-81a19d289000)

### 🖥️ Environment (if applicable):
- **Browser**: (Chrome)

Please assigned to me

**Comment by param-code** [comment]
> # 🐞 Bug Report
> ### 📋 Description
> When we try to login and create account they show me a form but in form there are some inputs but no input suggest any thing placeholder of every input is missing.
> 
> ### ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to login page and signup page.
> 2. Give placeholder to every input.
> 
> ### ✔️ Expected Behavior
> When input have a placeholder so interaction of user is increased!
> 
> ### ❌ Actual Behavior
> In form it shows only input tag no suggestion available
> 
> ### 📷 Screenshots
> ![placeholder](https://private-user-images.githubusercontent.com/165468244/375920925-ffbad680-5d9b-4f33-afaf-81a19d289000.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDUzNDAsIm5iZiI6MTcyODcwNTA0MCwicGF0aCI6Ii8xNjU0NjgyNDQvMzc1OTIwOTI1LWZmYmFkNjgwLTVkOWItNGYzMy1hZmFmLTgxYTE5ZDI4OTAwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMzUwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzE2NzEyZWIzYzczYjU5OTdkYTBjMDc1MjY1NjA0ZjE4NWQ1NzI4NjA4Y2Y2MGFlM2EwMzIxNjE1YjExZmNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.toE9g4p5EcUrnkGfPXMxP-kFO-2efxvQM6lIdFPkgXE)
> 
> ### 🖥️ Environment (if applicable):
> * **Browser**: (Chrome)
> 
> Please assigned to me

Sure.All the Best.
