### ISSUE TITLE
[Bug]: Double border in Login and Signup page

### ISSUE THREAD

**Issue by harshbhar0629** [param-code/counter-app#112]
# 🐞 Bug Report

### 📋 Description
When we click on input tag in login and signup from then an unexpected border is coming it show me 2 border around the tag.

### ⚙️ Steps to Reproduce
1. Go to login and signup form
2. Edit the border in your case it show 2 border.

### ✔️ Expected Behavior
When we click on input tag it will show a single border.

### ❌ Actual Behavior
When we click on input tag it will show 2 border around us.

### 📷 Screenshots

![double-border](https://github.com/user-attachments/assets/101e1e59-62a8-40c3-81fb-f3d057354363)

### 🖥️ Environment (if applicable):
- **OS**: (Windows)
- **Browser**: (Chrome)

Please assign to me this issue

**Comment by param-code** [comment]
> # 🐞 Bug Report
> ### 📋 Description
> When we click on input tag in login and signup from then an unexpected border is coming it show me 2 border around the tag.
> 
> ### ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to login and signup form
> 2. Edit the border in your case it show 2 border.
> 
> ### ✔️ Expected Behavior
> When we click on input tag it will show a single border.
> 
> ### ❌ Actual Behavior
> When we click on input tag it will show 2 border around us.
> 
> ### 📷 Screenshots
> ![double-border](https://private-user-images.githubusercontent.com/165468244/375923098-101e1e59-62a8-40c3-81fb-f3d057354363.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDczODcsIm5iZiI6MTcyODcwNzA4NywicGF0aCI6Ii8xNjU0NjgyNDQvMzc1OTIzMDk4LTEwMWUxZTU5LTYyYTgtNDBjMy04MWZiLWYzZDA1NzM1NDM2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNDI0NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGM2MThhZDg3NzFlNzVlOTQ1YTczNGZhMmUyZGQzYTIwMzYyOTQ4MzM4OWVlYjU0ZTNjMTkyY2Y4NWUzZTRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fJXtgznkxzFjXB1PLvRdEVzoUtU-PxJSIPDi679rMxQ)
> 
> ### 🖥️ Environment (if applicable):
> * **OS**: (Windows)
> * **Browser**: (Chrome)
> 
> Please assign to me this issue

-_-
