### ISSUE TITLE
[Feature]: Notification after login and signup

### ISSUE THREAD

**Issue by harshbhar0629** [param-code/counter-app#114]
# 🚀 Feature Request

### 📝 Feature Description
When we click on login and signup then it will navigate to home page and also give notification of successfully login and successfully signup.

### 🔧 How Will This Enhance the App?
We will use to react-hot-toast when the login and signup button trigger then it navigates to home page and also show notification of successfully login or signup

### 🎯 Use Cases
It increases the user attraction towards the app because of notification.

### 📦 Suggested Implementation
When login or signup button click then the onClick event will trigger and it show the toast.success("login Successfully "Successfully ) or toast.success("Signup Successfully ").

### 📸 Additional Context

https://github.com/user-attachments/assets/52b82efa-1937-4349-91b9-6959d7ca1419

@param-code  Please assign to me:)

**Comment by param-code** [comment]
Okay Man..
