### ISSUE TITLE
[Bug]: Confirm password is missing

### ISSUE THREAD

**Issue by harshbhar0629** [param-code/counter-app#116]
# 🐞 Bug Report

### 📋 Description
Confirm password is missing in signup page.

### ⚙️ Steps to Reproduce
1. Go to signup page
2. Add Confirm password input field with the label

### ✔️ Expected Behavior
When user try to create account then it can't put password randomly it also check its password again by confirming password.

### ❌ Actual Behavior
No confirm password option is there.

### 📷 Screenshots

![cpasswordMissing](https://github.com/user-attachments/assets/cf00e7b1-e5b6-4ac7-851f-dc72c9327c33)

### 🖥️ Environment (if applicable):
- **OS**: (Windows)
- **Browser**: (Chrome)

@param-code Please assign to me this issue with the labels.

**Comment by harshbhar0629** [comment]
@param-code ??

**Comment by nandu-99** [comment]
Please assign me this issue @harshbhar0629 , i want to work on this, and resolve this as soon as possible

**Comment by harshbhar0629** [comment]
I'm not maintainer i'm asking to resolve this bug.

**Comment by param-code** [comment]
Already there now.
