### ISSUE TITLE
[Bug]: No password view button

### ISSUE THREAD

**Issue by harshbhar0629** [param-code/counter-app#117]
# 🐞 Bug Report

### 📋 Description
There is no option by which we can view our password.

### ⚙️ Steps to Reproduce
1. Go to signup and login page 
2. We can manage the state of view and not view password by useState hook.

### ✔️ Expected Behavior
When we click on eye button then it show password then again we click onCloseEye button then it hide password.

### ❌ Actual Behavior
We can enter our password but we can't view what we are entering in password.

### 📷 Screenshots

![noPasswordViewBtn](https://github.com/user-attachments/assets/aeae563f-6ac6-4ff3-81a0-c08d9f25e5f6)

### 🖥️ Environment (if applicable):
- **OS**: (Windows)
- **Browser**: (Chrome)
- **Version**: (if relevant)

Please assign to me with the labels @param-code .

**Comment by param-code** [comment]
It's there now.
