### ISSUE TITLE
[Bug]: Signin/Signup Functionalities Not Working Properly – Data Not Being Stored

### ISSUE THREAD

**Issue by nandu-99** [param-code/counter-app#118]
# 🐞 Bug Report

### 📋 Description
The signup and signin functionalities are not working as expected. It is possible to signin without signing up, and user data is not being stored anywhere.

### ⚙️ Steps to Reproduce
1. Attempt to signup using the API.
2. Try to signin without a successful signup.
3. Observe that signin succeeds despite no user data being stored.

### ✔️ Expected Behavior
- A user should not be able to signin unless they have signed up and their data has been stored.
- User data should be stored properly upon signup.

### ❌ Actual Behavior
- Signin works even without a prior signup.
- No data is stored when a user signs up.

### 📷 
Uploading Screen Recording 2024-10-12 at 11.24.04 AM.mov…

### 🖥️ Environment:
- **OS**: macOS
- **Browser**: Chrome
- **Version**: 116.0.5845.96

### 🔧 Additional Information
We can store the user data in Firebase or a custom backend.

### ⬇️ Request
I would like to work on this issue. Please assign it to me. You can also provide feedback or suggestions.

**Comment by param-code** [comment]
> # 🐞 Bug Report
> ### 📋 Description
> The signup and signin functionalities are not working as expected. It is possible to signin without signing up, and user data is not being stored anywhere.
> 
> ### ⚙️ Steps to Reproduce
> 1. Attempt to signup using the API.
> 2. Try to signin without a successful signup.
> 3. Observe that signin succeeds despite no user data being stored.
> 
> ### ✔️ Expected Behavior
> * A user should not be able to signin unless they have signed up and their data has been stored.
> * User data should be stored properly upon signup.
> 
> ### ❌ Actual Behavior
> * Signin works even without a prior signup.
> * No data is stored when a user signs up.
> 
> ### 📷
> Uploading Screen Recording 2024-10-12 at 11.24.04 AM.mov…
> 
> ### 🖥️ Environment:
> * **OS**: macOS
> * **Browser**: Chrome
> * **Version**: 116.0.5845.96
> 
> ### 🔧 Additional Information
> We can store the user data in Firebase or a custom backend.
> 
> ### ⬇️ Request
> I would like to work on this issue. Please assign it to me. You can also provide feedback or suggestions.

Sure.All the Best @nandu-99 .

**Comment by param-code** [comment]
> > # 🐞 Bug Report
> > ### 📋 Description
> > The signup and signin functionalities are not working as expected. It is possible to signin without signing up, and user data is not being stored anywhere.
> > ### ⚙️ Steps to Reproduce
> > 
> > 1. Attempt to signup using the API.
> > 2. Try to signin without a successful signup.
> > 3. Observe that signin succeeds despite no user data being stored.
> > 
> > ### ✔️ Expected Behavior
> > 
> > * A user should not be able to signin unless they have signed up and their data has been stored.
> > * User data should be stored properly upon signup.
> > 
> > ### ❌ Actual Behavior
> > 
> > * Signin works even without a prior signup.
> > * No data is stored when a user signs up.
> > 
> > ### 📷
> > Uploading Screen Recording 2024-10-12 at 11.24.04 AM.mov…
> > ### 🖥️ Environment:
> > 
> > * **OS**: macOS
> > * **Browser**: Chrome
> > * **Version**: 116.0.5845.96
> > 
> > ### 🔧 Additional Information
> > We can store the user data in Firebase or a custom backend.
> > ### ⬇️ Request
> > I would like to work on this issue. Please assign it to me. You can also provide feedback or suggestions.
> 
> Sure.All the Best @nandu-99 .

Got resolved already now.
