### ISSUE TITLE
[Bug]: No error handling for invalid inputs or edge cases like negative numbers, in timer.

### ISSUE THREAD

**Issue by Veda273** [param-code/counter-app#124]
# 🐞 Bug Report

### 📋 Description
The timer  lacks clear feedback when starting, pausing, or resetting, leading to user confusion. Additionally, there's no visual cue or alert for invalid inputs like negative numbers.

### ⚙️ Steps to Reproduce
1. Open the app.
2.Enter a negative number in the counter or timer.
3.Attempt to start or reset without feedback.

### ✔️ Expected Behavior
A clear, visible indicator showing successful actions and handling of invalid input.

### ❌ Actual Behavior
No feedback is provided, leaving the user unaware of the app's state.

### 📷 Screenshots
![Screenshot 2024-10-12 152108](https://github.com/user-attachments/assets/8c19316c-27e8-433b-b73e-261cdabfe0f5)

@Paramveer Singh, please assign me this issue , under gssoc-extend

**Comment by param-code** [comment]
> # 🐞 Bug Report
> ### 📋 Description
> The timer lacks clear feedback when starting, pausing, or resetting, leading to user confusion. Additionally, there's no visual cue or alert for invalid inputs like negative numbers.
> 
> ### ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> 1. Open the app.
>    2.Enter a negative number in the counter or timer.
>    3.Attempt to start or reset without feedback.
> 
> ### ✔️ Expected Behavior
> A clear, visible indicator showing successful actions and handling of invalid input.
> 
> ### ❌ Actual Behavior
> No feedback is provided, leaving the user unaware of the app's state.
> 
> ### 📷 Screenshots
> ![Screenshot 2024-10-12 152108](https://private-user-images.githubusercontent.com/100017640/375948529-8c19316c-27e8-433b-b73e-261cdabfe0f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDgyMDEsIm5iZiI6MTcyODgwNzkwMSwicGF0aCI6Ii8xMDAwMTc2NDAvMzc1OTQ4NTI5LThjMTkzMTZjLTI3ZTgtNDMzYi1iNzNlLTI2MWNkYWJmZTBmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwODI1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOTUyOGJhMWI0ODkyNDdlYzI1MTcxMmVmZDZiNGI5NThlMmZjNTVmMWE2ZWM4MGRkZmVjZDFlMmJiYWQzMWZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QOM911lDABW2hjDSHt9s5DK0SxqgsgqOsJw2OXAf6T4)
> 
> @paramveer Singh, please assign me this issue , under gssoc-extend

All the Best!!
