### ISSUE TITLE
[Feature]: Add 'Close (X)' Button to Login and Signup Windows for Redirecting to Homepage

### ISSUE THREAD

**Issue by Ayan-Khan79** [param-code/counter-app#125]
# 🚀 Feature Request

### 📝 Feature Description
Add a close ("X") button to the login and signup modals that allows users to exit the modal and automatically redirects them to the homepage. This feature enhances user experience by providing an easy way to exit the authentication flow without manually navigating back to the homepage.

### 🔧 How Will This Enhance the App?

- Improved User Experience (UX):
    - Provides a quick and intuitive exit option from login and sign-up windows.
    - Reduces friction for users who don’t want to proceed with the form.
- Increased Flexibility for Navigation:
  - Enables immediate redirection to the homepage, keeping users engaged with the rest of the site.
- Enhanced App Accessibility:
    - Adds a clear visual cue (the "X" button) for users to easily close the modal.
![image](https://github.com/user-attachments/assets/bffaa524-75ba-4dd4-803b-4458f293974e)
![image](https://github.com/user-attachments/assets/63f6c8cb-e2d5-4b1e-af85-cec77e358754)

Both the pages dont have this functionality

@param-code Please assign me this issue under gssoc and hacktoberfest label, so I can start working on it....

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> Add a close ("X") button to the login and signup modals that allows users to exit the modal and automatically redirects them to the homepage. This feature enhances user experience by providing an easy way to exit the authentication flow without manually navigating back to the homepage.
> 
> ### 🔧 How Will This Enhance the App?
> * Improved User Experience (UX):
>   
>   * Provides a quick and intuitive exit option from login and sign-up windows.
>   * Reduces friction for users who don’t want to proceed with the form.
> * Increased Flexibility for Navigation:
>   
>   * Enables immediate redirection to the homepage, keeping users engaged with the rest of the site.
> * Enhanced App Accessibility:
>   
>   * Adds a clear visual cue (the "X" button) for users to easily close the modal.
>     ![image](https://private-user-images.githubusercontent.com/151816474/375956902-bffaa524-75ba-4dd4-803b-4458f293974e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDgwNzksIm5iZiI6MTcyODgwNzc3OSwicGF0aCI6Ii8xNTE4MTY0NzQvMzc1OTU2OTAyLWJmZmFhNTI0LTc1YmEtNGRkNC04MDNiLTQ0NThmMjkzOTc0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwODIyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmI4YzI5ODQ1ZDU3OGVkMmJjNmQ0NTRkZDhhZTRiNzYzOWI1ZGY4ZDg4NzUzMGJlMzk3Mjg5MzgyMDcwYjY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5TTBiNekOBxDKMOA086bdLMElzJvyRaruj1uoMVLntw)
>     ![image](https://private-user-images.githubusercontent.com/151816474/375956905-63f6c8cb-e2d5-4b1e-af85-cec77e358754.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDgwNzksIm5iZiI6MTcyODgwNzc3OSwicGF0aCI6Ii8xNTE4MTY0NzQvMzc1OTU2OTA1LTYzZjZjOGNiLWUyZDUtNGIxZS1hZjg1LWNlYzc3ZTM1ODc1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwODIyNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOGFlODEzOTAxZjE5NmE2MTY4MjNlNjMyMzI1NGUzNjkxODQ2ZDgyZTY1MDE3NGQ2MTI5NmY2ZDFkY2Q5ZWUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lvhDbtHYkCS7Kw3ynDuMYRlvxq7279NyfC-_logEIQk)
> 
> Both the pages dont have this functionality
> 
> @param-code Please assign me this issue under gssoc and hacktoberfest label, so I can start working on it....

All the Best!!
