### ISSUE TITLE
[Bug]: Removing Background adding new animated background ( webpage lagging too much )

### ISSUE THREAD

**Issue by devxMani** [param-code/counter-app#131]
# 🐞 Bug Report

### 📋 Description
there is so much lag in the website because of this background so I have to apply new animated background with simple effects not like this one

### ⚙️ Steps to Reproduce
1. remove old bg
2. add new bg
3.  
CAN YOU ADD GSOC EXT LEVEL 3 to this 

https://github.com/user-attachments/assets/fa8e31d4-b2b8-4fb2-b9b6-8db86b04c758

### 🖥️ Environment (if applicable):
- **OS**: (e.g., Windows, macOS, Linux)
- **Browser**: (e.g., Chrome, Safari, Firefox)
- **Version**: (if relevant)

**Comment by param-code** [comment]
For getting level 3 you need to make some significant change.And about bg I think it is quite good.
