### ISSUE TITLE
[Feature]: Login and signup backend

### ISSUE THREAD

**Issue by harshbhar0629** [param-code/counter-app#132]
# 🚀 Feature Request

### 📝 Feature Description
We want login and signup feature it depends on email and password no two account exist for same email with the error handling. 

### 🔧 How Will This Enhance the App?
If login and signup functionality integrate then no same account is occur and only valid account is occur which is stored in db: Database. 

### 🎯 Use Cases
You can easily implement authentication and authorization using login and signup.

### 📦 Suggested Implementation

![373210404-9f42b9d0-8e82-4e9b-acc9-f9ac4bae98ff](https://github.com/user-attachments/assets/eadf9542-b67c-477b-a264-3de96e16a9ad)

Folder Structure
BACKEND
Backend: It contains the whole backend of login and signup functionality.
Config: It connect the node environment to the database with dbConnect() function.
Controllers: In controllers there is a auth.js which is related to the authentication with all validation and i also used hashing(Bcrypt package) for to secure the password and also used Json-Web-Token for validation of token. No same user can create an account on this platform via same email address.
Models: There is only one model which is User model contains ["Firstname", "Lastname", "Email", "Password", "image-url", "token"].
.env file: In this file there are 3 deafult value you can add or edit accordingly
MONGODB_URL = mongodb://127.0.0.1:27017/ It req database url
JWT_SECRET = "MYSECRET" Select your token
PORT = 4000 Enter your port number

Index.js: There is basic setup of express and also used middlewares for parsing data.

UI
Components/Auth : There are 3 components are there Template.js LoginForm.js, SignupForm.js On the basis of condition I render Login and signupform respectively! There is simple setup for login and signup using tailwindCSS.
SignupForm : When user click on create account we call to backend for creating a user and also show toast for interactive UI.
LoginForm : When user click on Sign in we call to backend for checking this user exist or not and also hashed their password for matching this is same passsword or not.

Reducer: We combine all the reducer or slices which is used in login and signup functionality.
Slices: We create two slices 1. authSlice which mainly holds token and profileSlice contains the user data for future purpose like for creating a dashboard of user then data will be required so I secured all data for now!.
Services/operations: Inside operations there is one file authAPI which connects or call the backend from the client side and send response accordingly, There are 3 main functions are there LOGIN, SIGNUP, LOGOUT, In login and signup we take data from client side and make a call to apiConnector to pass the given data and show response accordingly!

Services/apiConnector.js: In this file it only recieve the given data from client side and return an axios instance with taking the method of call, data, url, headers, params

Services/api.js: In this file I'm mentioning the all routes of backend which is used in login and signup functionality!.

App.js: In App.js I'm creating a home page so every listing and everything lie on Home page and also create a route for login and signup.

Index.js: I just wrapped the App component in Provider of react-redux.
.env: It having REACT_BASE_URL you can edit acccordingly!

I also setup for tailwindCSS.

Now executable command is changed so Enter: npm run dev so that backend and frontend starts immediately! Please remeber the commands:) and also updates in readme.md file.

@param-code Please review it and assign to me under gssoc-ext and hacktoberfest-accepted with the level-3 because it required alot of code.

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> We want login and signup feature it depends on email and password no two account exist for same email with the error handling.
> 
> ### 🔧 How Will This Enhance the App?
> If login and signup functionality integrate then no same account is occur and only valid account is occur which is stored in db: Database.
> 
> ### 🎯 Use Cases
> You can easily implement authentication and authorization using login and signup.
> 
> ### 📦 Suggested Implementation
> ![373210404-9f42b9d0-8e82-4e9b-acc9-f9ac4bae98ff](https://private-user-images.githubusercontent.com/165468244/375991489-eadf9542-b67c-477b-a264-3de96e16a9ad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MDc5NDMsIm5iZiI6MTcyODgwNzY0MywicGF0aCI6Ii8xNjU0NjgyNDQvMzc1OTkxNDg5LWVhZGY5NTQyLWI2N2MtNDc3Yi1hMjY0LTNkZTk2ZTE2YTlhZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QwODIwNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWZkNGM0M2JiMWQ1Yzk5NGE3NmMwMWRmZmZhYTI5YTg1YmJjM2I4ZDc5YmNlYWFiMGIzZWU1YmM3ODM3ZDM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pej76uQFISm9PfVQPUnFVW9pOeh8bnchRFTHnmTxVp0)
> 
> Folder Structure BACKEND Backend: It contains the whole backend of login and signup functionality. Config: It connect the node environment to the database with dbConnect() function. Controllers: In controllers there is a auth.js which is related to the authentication with all validation and i also used hashing(Bcrypt package) for to secure the password and also used Json-Web-Token for validation of token. No same user can create an account on this platform via same email address. Models: There is only one model which is User model contains ["Firstname", "Lastname", "Email", "Password", "image-url", "token"]. .env file: In this file there are 3 deafult value you can add or edit accordingly MONGODB_URL = mongodb://127.0.0.1:27017/ It req database url JWT_SECRET = "MYSECRET" Select your token PORT = 4000 Enter your port number
> 
> Index.js: There is basic setup of express and also used middlewares for parsing data.
> 
> UI Components/Auth : There are 3 components are there Template.js LoginForm.js, SignupForm.js On the basis of condition I render Login and signupform respectively! There is simple setup for login and signup using tailwindCSS. SignupForm : When user click on create account we call to backend for creating a user and also show toast for interactive UI. LoginForm : When user click on Sign in we call to backend for checking this user exist or not and also hashed their password for matching this is same passsword or not.
> 
> Reducer: We combine all the reducer or slices which is used in login and signup functionality. Slices: We create two slices 1. authSlice which mainly holds token and profileSlice contains the user data for future purpose like for creating a dashboard of user then data will be required so I secured all data for now!. Services/operations: Inside operations there is one file authAPI which connects or call the backend from the client side and send response accordingly, There are 3 main functions are there LOGIN, SIGNUP, LOGOUT, In login and signup we take data from client side and make a call to apiConnector to pass the given data and show response accordingly!
> 
> Services/apiConnector.js: In this file it only recieve the given data from client side and return an axios instance with taking the method of call, data, url, headers, params
> 
> Services/api.js: In this file I'm mentioning the all routes of backend which is used in login and signup functionality!.
> 
> App.js: In App.js I'm creating a home page so every listing and everything lie on Home page and also create a route for login and signup.
> 
> Index.js: I just wrapped the App component in Provider of react-redux. .env: It having REACT_BASE_URL you can edit acccordingly!
> 
> I also setup for tailwindCSS.
> 
> Now executable command is changed so Enter: npm run dev so that backend and frontend starts immediately! Please remeber the commands:) and also updates in readme.md file.
> 
> @param-code Please review it and assign to me under gssoc-ext and hacktoberfest-accepted with the level-3 because it required alot of code.

If you made the changes as you have here then only I will provide your PR level 3.All the Best!!
