### ISSUE TITLE
[Feature]: Spotify or some music player embedding

### ISSUE THREAD

**Issue by param-code** [param-code/counter-app#140]
# 🚀 Feature Request

### 📝 Feature Description
Does anyone wants to code a feature that will embedded some player in the site which user can use while study sessions.It will play some lo-fi music or soothing songs Randomly.

**Comment by Saaarthak0102** [comment]
I am a newbie...but I would love to try this!

**Comment by param-code** [comment]
> I am a newbie...but I would love to try this!

Sure Sure.

**Comment by Saaarthak0102** [comment]
will take 2-3 days to learn this! please do not assign it to someone else!
I will tag if u i am not able to do this!
thank you!

**Comment by param-code** [comment]
> will take 2-3 days to learn this! please do not assign it to someone else! I will tag if u i am not able to do this! thank you!

Okay.All the Best!!
