### ISSUE TITLE
[Feature]: Build a "Contact Us" Page

### ISSUE THREAD

**Issue by Rahul-AkaVector** [param-code/counter-app#143]
# 🚀 Feature Request

### 📝 Feature Description
I would like to propose the development of a "Contact Us" page for website. This page will serve as a direct communication channel for users to reach out with their inquiries, feedback, or suggestions. Below are the features and requirements for the page:

**Features:**

1. **Form Fields:**
   - **Name:** A field for users to enter their name.
   - **Email:** A field for users to provide their email address.
   - **Subject:** A field to specify the subject of their message.
   - **Message:** A larger text area for users to type their message.

2. **Validation:**
   - Implement validation for the input fields to ensure that:
     - The name and email fields are not empty.
     - The email address is in a valid format.
     - The message field is not empty.

3. **Responsive Design:**
   - The page will be fully responsive, ensuring a seamless user experience across devices (desktop, tablet, and mobile).

4. **Attractive UI Design:**
   - The design will be visually appealing and consistent with the overall theme of the website.

5. **Navigation:**
   - The page will be easily accessible through useful links in the footer.

6. **Submission Feedback:**
   - Upon successful form submission, a proper popup will notify users of their successful submission or any errors encountered.

### 🔧 How Will This Enhance the App?
This "Contact Us" page will enhance user experience by providing a straightforward and effective way for users to communicate with the team. It will encourage user feedback and improve engagement.

### 🎯 Use Cases
- Users want to provide feedback or report issues they encounter.
- Potential customers may have questions about services or features.
- Visitors may want to reach out for collaboration opportunities.

### 📦 Suggested Implementation
- Create a new page/component for the "Contact Us" form.
- Implement form fields with appropriate validation and feedback mechanisms.
- Style the page to match the website's theme and ensure responsiveness.
- Add the new page to the footer navigation links for easy access.

### 📸 Additional Context
If there are any existing design guidelines or components in the repository that I should follow, please let me know. I’m excited to contribute to this feature and enhance the website’s functionality!

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> I would like to propose the development of a "Contact Us" page for website. This page will serve as a direct communication channel for users to reach out with their inquiries, feedback, or suggestions. Below are the features and requirements for the page:
> 
> **Features:**
> 
> 1. **Form Fields:**
>    
>    * **Name:** A field for users to enter their name.
>    * **Email:** A field for users to provide their email address.
>    * **Subject:** A field to specify the subject of their message.
>    * **Message:** A larger text area for users to type their message.
> 2. **Validation:**
>    
>    * Implement validation for the input fields to ensure that:
>      
>      * The name and email fields are not empty.
>      * The email address is in a valid format.
>      * The message field is not empty.
> 3. **Responsive Design:**
>    
>    * The page will be fully responsive, ensuring a seamless user experience across devices (desktop, tablet, and mobile).
> 4. **Attractive UI Design:**
>    
>    * The design will be visually appealing and consistent with the overall theme of the website.
> 5. **Navigation:**
>    
>    * The page will be easily accessible through useful links in the footer.
> 6. **Submission Feedback:**
>    
>    * Upon successful form submission, a proper popup will notify users of their successful submission or any errors encountered.
> 
> ### 🔧 How Will This Enhance the App?
> This "Contact Us" page will enhance user experience by providing a straightforward and effective way for users to communicate with the team. It will encourage user feedback and improve engagement.
> 
> ### 🎯 Use Cases
> * Users want to provide feedback or report issues they encounter.
> * Potential customers may have questions about services or features.
> * Visitors may want to reach out for collaboration opportunities.
> 
> ### 📦 Suggested Implementation
> * Create a new page/component for the "Contact Us" form.
> * Implement form fields with appropriate validation and feedback mechanisms.
> * Style the page to match the website's theme and ensure responsiveness.
> * Add the new page to the footer navigation links for easy access.
> 
> ### 📸 Additional Context
> If there are any existing design guidelines or components in the repository that I should follow, please let me know. I’m excited to contribute to this feature and enhance the website’s functionality!

All the Best!! Feel free to make the appropriate changes.
