### ISSUE TITLE
Missing Navbar in contributors page

### ISSUE THREAD

**Issue by Saaarthak0102** [param-code/counter-app#144]
## 📋 Description
The navigation bar is missing on the Contributors page, causing navigation inconsistencies across the website.

## ⚙️ Steps to Reproduce

Open the website and navigate to the Contributors page.
Observe the absence of the navigation bar.
Try to navigate back or to other sections without the navigation bar.

## ✔️ Expected Behavior
The navigation bar should appear on the Contributors page, allowing users to navigate to other parts of the website easily.

## ❌ Actual Behavior
The navigation bar is missing, limiting navigation on the Contributors page.

## 📷 Screenshots
![image](https://github.com/user-attachments/assets/fa0d2a8e-acda-431c-ad03-6621d9b14a03)

## 🔧 Additional Information
The issue seems specific to the Contributors page. Other pages on the site have a visible and functional navigation bar.

**Comment by param-code** [comment]
> ## 🐞 Bug Report
> ## 📋 Description
> The navigation bar is missing on the Contributors page, causing navigation inconsistencies across the website.
> 
> ## ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> Open the website and navigate to the Contributors page. Observe the absence of the navigation bar. Try to navigate back or to other sections without the navigation bar.
> 
> ## ✔️ Expected Behavior
> The navigation bar should appear on the Contributors page, allowing users to navigate to other parts of the website easily.
> 
> ## ❌ Actual Behavior
> The navigation bar is missing, limiting navigation on the Contributors page.
> 
> ## 📷 Screenshots
> ![image](https://private-user-images.githubusercontent.com/174188123/376032317-fa0d2a8e-acda-431c-ad03-6621d9b14a03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MjIwNzUsIm5iZiI6MTcyODgyMTc3NSwicGF0aCI6Ii8xNzQxODgxMjMvMzc2MDMyMzE3LWZhMGQyYThlLWFjZGEtNDMxYy1hZDAzLTY2MjFkOWIxNGEwMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxMjE2MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGEwMjAyZTFkMjdkYjM0NzJlM2UyMjIxOTNkOTdkN2Q2NTYwZDUzNjZhZDZjMWIxZTgyMjc5OWM4YzYzYTVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hth61qnpRhFf6l6p7l0erhZLVszbAL-Q8ja2xGIF_xg)
> 
> ## 🔧 Additional Information
> The issue seems specific to the Contributors page. Other pages on the site have a visible and functional navigation bar.

Okay.Do what you want.

**Comment by Saaarthak0102** [comment]
merged
