### ISSUE TITLE
✨[Feature]: Improving signup page routing✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [param-code/counter-app#145]
Once you go to the signup page, there is no button to go back to home. If you can assign this task, I'll add a bottle redirect to homepage.

<img width="794" alt="Screenshot 2024-10-13 at 7 39 48 PM" src="https://github.com/user-attachments/assets/8e2606cc-64e0-4a5e-adcc-c435643af4f9">

**Comment by T-Rahul-prabhu-38** [comment]
@param-code can you assign me this task.

**Comment by param-code** [comment]
> @param-code can you assign me this task.

This feature has already got added.
