### ISSUE TITLE
[Feature]: fixing the login page logic

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [param-code/counter-app#146]
# 🚀 Feature Request

the signup page works but the login page doesnt allow you to login even after correct creentials are entered.
@param-code can you assign me this task to work on this feature.

<img width="550" alt="Screenshot 2024-10-13 at 7 42 10 PM" src="https://github.com/user-attachments/assets/6f835761-7649-45f9-9e6e-6f7dd10ec86d">

**Comment by param-code** [comment]
> # 🚀 Feature Request
> the signup page works but the login page doesnt allow you to login even after correct creentials are entered. @param-code can you assign me this task to work on this feature.
> 
> <img alt="Screenshot 2024-10-13 at 7 42 10 PM" width="550" src="https://private-user-images.githubusercontent.com/167653990/376041408-6f835761-7649-45f9-9e6e-6f7dd10ec86d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MzQ5OTUsIm5iZiI6MTcyODgzNDY5NSwicGF0aCI6Ii8xNjc2NTM5OTAvMzc2MDQxNDA4LTZmODM1NzYxLTc2NDktNDVmOS05ZTZlLTZmN2RkMTBlYzg2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxNTUxMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWU5NjA0OTM5OTMzYWI4MzlmOGFlYWQxNzBhMzExYWFiZDUzMmM3Mzc0YzM5ZGM4ZTczZmVlYWJjNGU4MTc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kEj5Nhg92qrOXYcWpkiqvat5Xcpc03xVgIutkJzgp-w">

Okay.All the Best!!

**Comment by param-code** [comment]
> > # 🚀 Feature Request
> > the signup page works but the login page doesnt allow you to login even after correct creentials are entered. @param-code can you assign me this task to work on this feature.
> > <img alt="Screenshot 2024-10-13 at 7 42 10 PM" width="550" src="https://private-user-images.githubusercontent.com/167653990/376041408-6f835761-7649-45f9-9e6e-6f7dd10ec86d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4MzQ5OTUsIm5iZiI6MTcyODgzNDY5NSwicGF0aCI6Ii8xNjc2NTM5OTAvMzc2MDQxNDA4LTZmODM1NzYxLTc2NDktNDVmOS05ZTZlLTZmN2RkMTBlYzg2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxM1QxNTUxMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWU5NjA0OTM5OTMzYWI4MzlmOGFlYWQxNzBhMzExYWFiZDUzMmM3Mzc0YzM5ZGM4ZTczZmVlYWJjNGU4MTc4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.kEj5Nhg92qrOXYcWpkiqvat5Xcpc03xVgIutkJzgp-w">
> 
> Okay.All the Best!!

This issue has got resolved.
