### ISSUE TITLE
[Bug]: Input Validation

### ISSUE THREAD

**Issue by harshbhar0629** [param-code/counter-app#149]
# 🐞 Bug Report

### 📋 Description
No Input validation in Signup form no regex check is applicable.

### ⚙️ Steps to Reproduce
1. Go to Signup page
2. Apply validation of regex check.

### ✔️ Expected Behavior
When regex check is applicable then it also check the password is contain number or alphabet or not and also check the input email validation and more.

### ❌ Actual Behavior
We can enter any email with contains @gmail.com and no matter what password is:)

### 🖥️ Environment (if applicable):
- **OS**: (Windows)
- **Browser**: (Chrome)

### 🔧 Additional Information
**Regex Check**
**Pattern Definition**: A regex pattern is defined using special characters, symbols, and text. For example, the pattern ^\d{3}-\d{2}-\d{4}$ represents a format for a Social Security Number (XXX-XX-XXXX), where \d matches any digit and {n} specifies the number of repetitions.

Checking/Matching: The regex is applied to a string to see if it conforms to the specified pattern. Depending on the use case, it can be used to:

Validate formats (e.g., phone numbers, email addresses).
Search for specific patterns within text (e.g., finding dates or keywords).
Split text into different components (e.g., tokenizing sentences).
Replace or modify parts of a string that match the pattern.

**Comment by param-code** [comment]
> # 🐞 Bug Report
> ### 📋 Description
> No Input validation in Signup form no regex check is applicable.
> 
> ### ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to Signup page
> 2. Apply validation of regex check.
> 
> ### ✔️ Expected Behavior
> When regex check is applicable then it also check the password is contain number or alphabet or not and also check the input email validation and more.
> 
> ### ❌ Actual Behavior
> We can enter any email with contains @gmail.com and no matter what password is:)
> 
> ### 🖥️ Environment (if applicable):
> * **OS**: (Windows)
> * **Browser**: (Chrome)
> 
> ### 🔧 Additional Information
> **Regex Check** **Pattern Definition**: A regex pattern is defined using special characters, symbols, and text. For example, the pattern ^\d{3}-\d{2}-\d{4}$ represents a format for a Social Security Number (XXX-XX-XXXX), where \d matches any digit and {n} specifies the number of repetitions.
> 
> Checking/Matching: The regex is applied to a string to see if it conforms to the specified pattern. Depending on the use case, it can be used to:
> 
> Validate formats (e.g., phone numbers, email addresses). Search for specific patterns within text (e.g., finding dates or keywords). Split text into different components (e.g., tokenizing sentences). Replace or modify parts of a string that match the pattern.

I have just merged your PR with level 3,you should have known this earlier.
