### ISSUE TITLE
Need more work on navbar

### ISSUE THREAD

**Issue by Suvadip-sana** [param-code/counter-app#15]
Hi! I am Suvadip, want to work on this project

![image](https://github.com/user-attachments/assets/2abcaa08-9e66-4b6e-958e-c4af16831bcb)

**ISSUE**
The navbar is too simple. I want to add more style and add a AI generated logo for this. 

Could you please assign me this issue?

**Comment by param-code** [comment]
Yeah sure!!Also you can create tabs for navigation between world clock,stopwatch & timer and feel free to add any features or design you like.All the Best!!

**Comment by Suvadip-sana** [comment]
OK

**Comment by Suvadip-sana** [comment]
Need clarification. 

Should I add  world clock,stopwatch & timer this tab means buttons in na bar? Or where? 
Please clarify this.

**Comment by Suvadip-sana** [comment]
@param-code Here is my changes ---> 


https://github.com/user-attachments/assets/d66f07f9-cd7b-4ec7-a84b-435a5c029794


Should I create a pull request?

**Comment by Suvadip-sana** [comment]
@HarshitShukla-dev @17arindam @param-code 
I create a pull request but but project owner not accept it till now.

**Comment by Suvadip-sana** [comment]
@param-code  please merge this pull request.
