### ISSUE TITLE
[Bug]: Negative timer

### ISSUE THREAD

**Issue by harshbhar0629** [param-code/counter-app#150]
# 🐞 Bug Report

### 📋 Description
There is a timer watch in which we have to give inputs and then it will decrease by one second and after all seconds finish then alert will be there but in input we can enter negative value.

### ⚙️ Steps to Reproduce
1. Go to timer
2. Set the timer field with min Value 0

### ✔️ Expected Behavior
When user try to set negative value then input will not take negative value.

### ❌ Actual Behavior
Now user can enter negative time in input filed.

### 📷 Screenshots

https://github.com/user-attachments/assets/606ba37c-bb00-4826-886e-e514362f170e

### 🖥️ Environment (if applicable):
- **OS**: (e.g., Windows)
- **Browser**: (Chrome)

Please assign to me this issue under the label of: gssoc-ext, hactoberfest-accepted with level-1,2,3.

**Comment by param-code** [comment]
> # 🐞 Bug Report
> ### 📋 Description
> There is a timer watch in which we have to give inputs and then it will decrease by one second and after all seconds finish then alert will be there but in input we can enter negative value.
> 
> ### ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to timer
> 2. Set the timer field with min Value 0
> 
> ### ✔️ Expected Behavior
> When user try to set negative value then input will not take negative value.
> 
> ### ❌ Actual Behavior
> Now user can enter negative time in input filed.
> 
> ### 📷 Screenshots
>  neg_timer.mp4 
> ### 🖥️ Environment (if applicable):
> * **OS**: (e.g., Windows)
> * **Browser**: (Chrome)
> 
> Please assign to me this issue under the label of: gssoc-ext, hactoberfest-accepted with level-1,2,3.

Okay!!
