### ISSUE TITLE
[Feature]: Creating About page

### ISSUE THREAD

**Issue by Hh440** [param-code/counter-app#151]
# 🚀 Feature Request

### 📝 Feature Description
This is feel the user celar understanding what does this website do and a medium the user can contact us.

### 🔧 How Will This Enhance the App?
the UI matches the website standards adn wll boost the visual appeal of the website

### 🎯 Use Cases
provide the infoemation about the usage and feature  of the wbsite 

![Screenshot from 2024-10-13 21-54-11](https://github.com/user-attachments/assets/570fd489-0d14-422a-8e85-305bdbaf0a5c)

**Comment by vivek1842** [comment]
would you assign me this issue?

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> This is feel the user celar understanding what does this website do and a medium the user can contact us.
> 
> ### 🔧 How Will This Enhance the App?
> the UI matches the website standards adn wll boost the visual appeal of the website
> 
> ### 🎯 Use Cases
> provide the infoemation about the usage and feature of the wbsite
> 
> ![Screenshot from 2024-10-13 21-54-11](https://private-user-images.githubusercontent.com/91595810/376051592-570fd489-0d14-422a-8e85-305bdbaf0a5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzY1ODksIm5iZiI6MTcyODg3NjI4OSwicGF0aCI6Ii85MTU5NTgxMC8zNzYwNTE1OTItNTcwZmQ0ODktMGQxNC00MjJhLThlODUtMzA1YmRiYWYwYTVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDAzMjQ0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiNzUyNTVjNzQyMGEyYmY3YzAwNjFmNWQ3ZTk2ODYzMmMxMzQwYWMwZmIwOGVmMTIwYTcwN2Q3OGEyNTJmMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3ho6BRhJdjJnGGJtgo8HEYOrptMY_8u6P5ogAiTZRow)

Okay.I am assigning this to you.

**Comment by Hh440** [comment]
Please make it level 2 atleast

**Comment by param-code** [comment]
> Please make it level 2 atleast

If your changes are good enough.
