### ISSUE TITLE
[Bug]: lap times aren't logging correctly

### ISSUE THREAD

**Issue by SheetalEdu** [param-code/counter-app#155]
# 🐞 Bug Report

### 📋 Description
 The "Lap" button in the **counter-timer-app** isn't logging lap times correctly after the timer starts, likely due to state management issues. It needs fixing to ensure laps are stored and displayed properly.

### ⚙️ Steps to Reproduce
1. Initialize Lap State Properly
2. Update State on Lap Button Click
3. Render Lap Times
4. Add Error Handling

### 📷 Screenshots
 

https://github.com/user-attachments/assets/74d87246-44a6-458a-b8be-29ee9956f8da

### 🔧 Additional Information
 Hi Param, I'd like to work on fixing the "Lap" button issue in the counter-timer-app where lap times aren't logging correctly—could you please assign this to me?

**Comment by param-code** [comment]
> # 🐞 Bug Report
> ### 📋 Description
> The "Lap" button in the **counter-timer-app** isn't logging lap times correctly after the timer starts, likely due to state management issues. It needs fixing to ensure laps are stored and displayed properly.
> ### ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> 1. Initialize Lap State Properly
> 2. Update State on Lap Button Click
> 3. Render Lap Times
> 4. Add Error Handling
> 
> ### 📷 Screenshots
>  Screen.Recording.2024-10-13.234751.mp4 
> ### 🔧 Additional Information
> Hi Param, I'd like to work on fixing the "Lap" button issue in the counter-timer-app where lap times aren't logging correctly—could you please assign this to me?

Sure.All the Best @SheetalEdu .

**Comment by SheetalEdu** [comment]
I quit!! It's working absolutely fine on phone.
