### ISSUE TITLE
[Custom]: Missing dockerignore file

### ISSUE THREAD

**Issue by vivekrawat21** [param-code/counter-app#156]
# 💡 Custom Issue

### 📝 Description

I noticed that the project is missing a Dockerfile, and I'd like to request the addition of a .dockerignore file as well. Both are critical for containerizing the application efficiently.

Why is a .dockerignore file important?
When building Docker images, the .dockerignore file plays a vital role in preventing unnecessary files from being copied to the Docker image, which can
Reduce image size: By excluding files like node_modules, logs, and other non-essential files, the Docker image can be kept lean, which improves performance and reduces disk usage.
Improve build performance: Skipping unnecessary files helps speed up the build process, especially in large projects.
Enhance security: Sensitive files like .env or configuration files that should not be exposed in the container can be excluded.

### 🔍 Steps to Reproduce (if applicable)
1. Create a file name as .dockerignore
2. Add the things you do not want to add to your image
3. Make your image light weight

### 🎯 Expected Outcome

￼￼Is there an existing issue raised for this?
Before reporting, kindly ensure that you dont duplicate an already existing issue.

￼ I have searched the existing issues *
Please fill out the sections below to properly describe the new improvements you are suggesting. Try to be as much detailed as possible.

Describe the improvement
Describe your idea which you would like to implement on an existing module. Add necessary prototypes or rough sketch or an overview on how you will be proceeding.

￼
Component
Which area of the application you are willing to improve? You may specify the URI of the screen.

￼
It should be implemented because
Give out a detailed explanation along with its use-case

￼
Would you like to work on this issue?
￼
None
￼￼Terms & Conditions
￼ I agree to follow the Code of Conduct *
￼ I'm a GSSOC'24 Ext contributor
Thanks for your suggestion! Let's see together if it can be implemented.

Fields marked with an asterisk (*) are required.

￼Submit new issue
Remember, contributions to this repository should follow its contributing guidelines and code of conduct.
Assignees
No one assigned
Labels
enhancement
Projects
None yet
Milestone
No milestone
Development
Shows branches and pull requests linked to this issue.

￼
￼

It looks like this is your first

**Comment by param-code** [comment]
> # 💡 Custom Issue
> ### 📝 Description
> I noticed that the project is missing a Dockerfile, and I'd like to request the addition of a .dockerignore file as well. Both are critical for containerizing the application efficiently.
> 
> Why is a .dockerignore file important? When building Docker images, the .dockerignore file plays a vital role in preventing unnecessary files from being copied to the Docker image, which can Reduce image size: By excluding files like node_modules, logs, and other non-essential files, the Docker image can be kept lean, which improves performance and reduces disk usage. Improve build performance: Skipping unnecessary files helps speed up the build process, especially in large projects. Enhance security: Sensitive files like .env or configuration files that should not be exposed in the container can be excluded.
> 
> ### 🔍 Steps to Reproduce (if applicable)
> 1. Create a file name as .dockerignore
> 2. Add the things you do not want to add to your image
> 3. Make your image light weight

If you think you can do something about that then feel free to move ahead.All the Best!!
