### ISSUE TITLE
fix the footer responsiveness 

### ISSUE THREAD

**Issue by gurramkarthiknetha** [param-code/counter-app#159]
<img width="736" alt="image" src="https://github.com/user-attachments/assets/f996b65c-fe14-4093-a3ab-e1796103200c">
and also
<img width="750" alt="image" src="https://github.com/user-attachments/assets/e8ad5f06-4ca2-4e70-8b94-20cb50adc0c3">
the lap is not aligned to center
Assign this issue to me I will fix it.

**Comment by param-code** [comment]
> <img alt="image" width="736" src="https://private-user-images.githubusercontent.com/167804249/376226281-f996b65c-fe14-4093-a3ab-e1796103200c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDc2OTAsIm5iZiI6MTcyODkwNzM5MCwicGF0aCI6Ii8xNjc4MDQyNDkvMzc2MjI2MjgxLWY5OTZiNjVjLWZlMTQtNDA5My1hM2FiLWUxNzk2MTAzMjAwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxMjAzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNDY0ZmRhNTM5OWNhYWRlZTBlZWYzZDUwNWVhYjJmYjI1ZDMxYjU2NGI4OTIyMWVkYmE5NjZjMjNjYWVmNzMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZOeKS5NV14TND4L2wqBANd57Djr2FFFimabFQx4vFWU"> and also <img alt="image" width="750" src="https://private-user-images.githubusercontent.com/167804249/376226583-e8ad5f06-4ca2-4e70-8b94-20cb50adc0c3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDc2OTAsIm5iZiI6MTcyODkwNzM5MCwicGF0aCI6Ii8xNjc4MDQyNDkvMzc2MjI2NTgzLWU4YWQ1ZjA2LTRjYTItNGU3MC04Yjk0LTIwY2I1MGFkYzBjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQxMjAzMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ZDM0ZTc4NWI3ODIwMDI0NDU3MTZmMDc5ZmI5YWM5MmRkZDU1MmJiYzY0NDg2ODg5ZDM0NzYxOGRjZGY4ZjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PNO94G6dPpYlpjuuGe3QFAR8ot6oj0jNUmfTuNE8yQ4"> the lap is not aligned to center Assign this issue to me I will fix it.

Okay.Let's see what you can do.
