### ISSUE TITLE
Need Enhancement of Button UI at Timer Tab

### ISSUE THREAD

**Issue by Abhiraj-Sardar** [param-code/counter-app#16]
Hey @param-code ,

I think the UI of the Buttons can be improved.
and I want to work on this... please assign me this task.

👇This is how the buttons look like
![button](https://github.com/user-attachments/assets/ee7975a8-9dc5-45a8-b57a-46103d29aff3)

please include the label of  **hacktoberfest2024**  in this issue. so that it can be counted under Hacktoberfest2024.

Thank you.

**Comment by param-code** [comment]
Sure!! Move ahead with your ideas!! All the Best!!

**Comment by Abhiraj-Sardar** [comment]
@param-code

The Issue of Button UI Enhancement is Done. 
I added some micro-animations in the button. You can see it here👇. 

https://github.com/user-attachments/assets/9b0b8842-cfdc-41de-b86a-26dbf6ca1207


Now You can close this Issue, if you find every thing OK.

**Comment by Abhiraj-Sardar** [comment]
@param-code 
please merge the Pull Request...
