### ISSUE TITLE
[Bug]: Sign up text in dark mode is not readable

### ISSUE THREAD

**Issue by Saaarthak0102** [param-code/counter-app#162]
# 🐞 Bug Report

### 📋 Description
"Sign Up" on Navbar is not readable in dark mode
![image](https://github.com/user-attachments/assets/7a8446a7-2a15-42e0-9179-91711acd0682)

## Expected behaviour
The text color must be white

**Comment by param-code** [comment]
> # 🐞 Bug Report
> ### 📋 Description
> "Sign Up" on Navbar is not readable in dark mode ![image](https://private-user-images.githubusercontent.com/174188123/376284490-7a8446a7-2a15-42e0-9179-91711acd0682.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NjM5MjcsIm5iZiI6MTcyODk2MzYyNywicGF0aCI6Ii8xNzQxODgxMjMvMzc2Mjg0NDkwLTdhODQ0NmE3LTJhMTUtNDJlMC05MTc5LTkxNzExYWNkMDY4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwMzQwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMmYxOGY3MWVlMzcxY2VmMTFhZWRhZmUzZDc5M2M5YmFhZTBlMWVmYWY4NzlkZjM5OTFlMzVlZmVhMjNjMzg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YzMiDoBziTY9XXaohcugiCOULvHSv2SPuBm2VAD6mZM)
> 
> ## Expected behaviour
> The text color must be white

Go and make the change. I don't think i can assign you any level but feel free to contribute.

**Comment by Saaarthak0102** [comment]
sure

**Comment by Saaarthak0102** [comment]
merged
