### ISSUE TITLE
[Bug]: Signup btn not visible in dark mode

### ISSUE THREAD

**Issue by harshbhar0629** [param-code/counter-app#166]
# 🐞 Bug Report

### 📋 Description
When we switch to dark mode then it will not show its text.

### ⚙️ Steps to Reproduce
1. Go to navbar 
2. Edit Signup btn Css

### ✔️ Expected Behavior
When we toggle the light mode to dark mode then signup btn also toggle its text color for it will be visible in website

### ❌ Actual Behavior
In dark mode it will not show in navbar only its border show:)

### 📷 Screenshots

![btn-not-visible](https://github.com/user-attachments/assets/a7e6a7a2-46c7-41a0-8884-fcd576ca025c)

### 🖥️ Environment (if applicable):
- **OS**: (Windows)
- **Browser**: (Chrome)

Please assign this issue  to me with labels:)

**Comment by param-code** [comment]
> # 🐞 Bug Report
> ### 📋 Description
> When we switch to dark mode then it will not show its text.
> 
> ### ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to navbar
> 2. Edit Signup btn Css
> 
> ### ✔️ Expected Behavior
> When we toggle the light mode to dark mode then signup btn also toggle its text color for it will be visible in website
> 
> ### ❌ Actual Behavior
> In dark mode it will not show in navbar only its border show:)
> 
> ### 📷 Screenshots
> ![btn-not-visible](https://private-user-images.githubusercontent.com/165468244/376343733-a7e6a7a2-46c7-41a0-8884-fcd576ca025c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTM0OTEsIm5iZiI6MTcyODk5MzE5MSwicGF0aCI6Ii8xNjU0NjgyNDQvMzc2MzQzNzMzLWE3ZTZhN2EyLTQ2YzctNDFhMC04ODg0LWZjZDU3NmNhMDI1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxMTUzMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YzEzNDFiMTVjMzIxZjBmZjI4MTE2YTBiMDU3MGY5YjVjNTUxY2EzMDAyYzQ4OWExOWI2NmUyODdjYjk5ODc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VqWh_S_B-4VU4PWNPQX34iNyfrFMQF_s4-BoDglCEE0)
> 
> ### 🖥️ Environment (if applicable):
> * **OS**: (Windows)
> * **Browser**: (Chrome)
> 
> Please assign this issue to me with labels:)

Let's see if you can make some good changes.
