### ISSUE TITLE
[Bug]: Spotify Music Player Window Appears Unexpectedly Near Language Selection

### ISSUE THREAD

**Issue by faiz66388** [param-code/counter-app#172]
Description:
When the cursor hovers near the "Select Language" dropdown, the Spotify music player window appears unexpectedly. This issue makes it difficult to click on the "Select Language" button, as the music player window overlaps it. The Spotify player should only appear when the cursor clicks on the Spotify icon, not when it just moves near it. The vicinity for triggering the player window seems too large.

Steps to Reproduce:
Open the website with the Spotify music player icon visible.
Move the cursor towards the "Select Language" button near the bottom of the page.
Observe that the Spotify player window appears without directly interacting with the icon.
Expected Behavior:
The Spotify music player window should only open when the user clicks directly on the Spotify icon.

Actual Behavior:
The Spotify music player window opens when the cursor hovers near the Spotify icon, making it difficult to select the language option.

Screenshots/Logs:
![Screenshot 2024-10-15 114128](https://github.com/user-attachments/assets/098cdc85-5aa8-4b80-8aaa-5132d27f9c56)
![image](https://github.com/user-attachments/assets/f61801c5-4eae-4614-9222-107d97dfc7df)

**Comment by SaumyaSubham** [comment]
I can work on this issue and Can you locate the file or folder that I'll work on so that I can get the file easily and start working on it!
Kindly assign me this issue under hacktoberfest 2024.

**Comment by param-code** [comment]
> Description: When the cursor hovers near the "Select Language" dropdown, the Spotify music player window appears unexpectedly. This issue makes it difficult to click on the "Select Language" button, as the music player window overlaps it. The Spotify player should only appear when the cursor clicks on the Spotify icon, not when it just moves near it. The vicinity for triggering the player window seems too large.
> 
> Steps to Reproduce: Open the website with the Spotify music player icon visible. Move the cursor towards the "Select Language" button near the bottom of the page. Observe that the Spotify player window appears without directly interacting with the icon. Expected Behavior: The Spotify music player window should only open when the user clicks directly on the Spotify icon.
> 
> Actual Behavior: The Spotify music player window opens when the cursor hovers near the Spotify icon, making it difficult to select the language option.
> 
> Screenshots/Logs: ![Screenshot 2024-10-15 114128](https://private-user-images.githubusercontent.com/143863916/376482366-098cdc85-5aa8-4b80-8aaa-5132d27f9c56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzY5ODksIm5iZiI6MTcyODk3NjY4OSwicGF0aCI6Ii8xNDM4NjM5MTYvMzc2NDgyMzY2LTA5OGNkYzg1LTVhYTgtNGI4MC04YWFhLTUxMzJkMjdmOWM1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwNzE4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZGZlZjJlNmM4NzUxYTNjNThmMzE3MTdlMTM1M2Y4MzM0NTljZGRlYmUxN2VlNDRkMzYzODU5YjIzMDZjNjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.q_kFkMxFjAd-uQ6p_63zOhwtCFKwSe-_vX-a706QvR4) ![image](https://private-user-images.githubusercontent.com/143863916/376482406-f61801c5-4eae-4614-9222-107d97dfc7df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NzY5ODksIm5iZiI6MTcyODk3NjY4OSwicGF0aCI6Ii8xNDM4NjM5MTYvMzc2NDgyNDA2LWY2MTgwMWM1LTRlYWUtNDYxNC05MjIyLTEwN2Q5N2RmYzdkZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwNzE4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hOGQzYWJlMmRiNTc1NjFjYTNjOGJkYWQ1YjE3NTI2YTEyMDUxZTE2OGNkNTBlZGNjMGQ5OTg3ZmNhMDQ3NmU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FcLZZOOhQiXcQB5uqBN4MYqPlRcLyEZxOuvxmeu2P8M)

Okay.Make the appropriate changes and send your PR.All the Best @faiz66388 .

**Comment by Sandigupta** [comment]
@param-code Please assign this issue to me.
thanks
