### ISSUE TITLE
Sign up page responsiveness is super messed up.

### ISSUE THREAD

**Issue by wajaht-ali** [param-code/counter-app#174]
Problem:-
The responsiveness of the app is not very compatible with mobile devices as the multiple components are overlayed by each other.

Solution:-
I can fix the issue by implementing the media queries since the app is using CSS for styling though it is easier to add this functionality.

![Uploading Screenshot 2024-10-15 121611.png…]()

**Comment by param-code** [comment]
someone is already working on this issue,you may wait till then.

**Comment by param-code** [comment]
> Sure!

You can still give it a try.
