### ISSUE TITLE
[Bug]: Dark mode is not functional in about us page

### ISSUE THREAD

**Issue by pranusri1903** [param-code/counter-app#176]
## 📋 Description

Dark mode is not functioning properly on the "About Us" page. When toggling dark mode, the theme remains in light mode for this specific page, while other pages switch to dark mode correctly.

## ⚙️ Steps to Reproduce

Navigate to the "About Us" page.
Toggle dark mode using the switch or button.
Observe that the "About Us" page does not reflect the dark mode.

## ✔️ Expected Behavior

When dark mode is toggled, the "About Us" page should switch to dark mode, matching the behavior of the other pages on the site.

##❌ Actual Behavior

The "About Us" page stays in light mode, even after dark mode is activated.

##📷 Screenshots

![image](https://github.com/user-attachments/assets/4fbf2ff6-8d88-4e06-8f39-532cdc637bec)

##🔧 Additional Information

This issue only occurs on the "About Us" page. All other pages respond correctly to the dark mode toggle.

**Comment by pranusri1903** [comment]
Please assign the issue to to me with the tags of gssoc, hacktober fest and the level which you see fit for the bug.

**Comment by param-code** [comment]
> ### 🐞 Bug Report
> ## 📋 Description
> Dark mode is not functioning properly on the "About Us" page. When toggling dark mode, the theme remains in light mode for this specific page, while other pages switch to dark mode correctly.
> 
> ## ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> Navigate to the "About Us" page. Toggle dark mode using the switch or button. Observe that the "About Us" page does not reflect the dark mode.
> 
> ## ✔️ Expected Behavior
> When dark mode is toggled, the "About Us" page should switch to dark mode, matching the behavior of the other pages on the site.
> 
> ##❌ Actual Behavior
> 
> The "About Us" page stays in light mode, even after dark mode is activated.
> 
> ##📷 Screenshots
> 
> ![image](https://private-user-images.githubusercontent.com/84591027/376543082-4fbf2ff6-8d88-4e06-8f39-532cdc637bec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTI1NjgsIm5iZiI6MTcyODk5MjI2OCwicGF0aCI6Ii84NDU5MTAyNy8zNzY1NDMwODItNGZiZjJmZjYtOGQ4OC00ZTA2LThmMzktNTMyY2RjNjM3YmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDExMzc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NTY5ZGE0MTc2YTI4MzM4MWM0Y2M3NmNiMmVlZGViMmJhNzI2NzdhNzY5ODAwYWU5Mzc0ZDQ3N2JkZDk1ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EFzkUEANVUj7M6xRQ904KTjf9Rkyg_qfaco5NHtej88)
> 
> ##🔧 Additional Information
> 
> This issue only occurs on the "About Us" page. All other pages respond correctly to the dark mode toggle.

If you think you can do it,move ahead.All the best!!
