### ISSUE TITLE
[Bug]: Dark mode is not functional on stopwatch page

### ISSUE THREAD

**Issue by Saaarthak0102** [param-code/counter-app#177]
## 📋 Description
Dark mode is not functioning properly on the "Stopwatch" page. When toggling dark mode, the theme remains in light mode for this specific page, while other pages switch to dark mode correctly.

## ⚙️ Steps to Reproduce

Navigate to the "Stopwatch " page through footer.
Toggle dark mode using the switch or button.
Observe that the "Stopwatch" page does not reflect the dark mode.

## Screenshot
![image](https://github.com/user-attachments/assets/2d11eb4e-c05d-4e44-8db7-e9e17ea827dd)

## ✔️ Expected Behavior
When dark mode is toggled, the "Stopwatch" page should switch to dark mode, matching the behavior of the other pages on the site.

## ❌ Actual Behavior

The "Stopwatch" page stays in light mode, even after dark mode is activated.

**Comment by param-code** [comment]
> ### 🐞 Bug Report
> ## 📋 Description
> Dark mode is not functioning properly on the "Stopwatch" page. When toggling dark mode, the theme remains in light mode for this specific page, while other pages switch to dark mode correctly.
> 
> ## ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> Navigate to the "Stopwatch " page through footer. Toggle dark mode using the switch or button. Observe that the "Stopwatch" page does not reflect the dark mode.
> 
> ## Screenshot
> ![image](https://private-user-images.githubusercontent.com/174188123/376551782-2d11eb4e-c05d-4e44-8db7-e9e17ea827dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5OTI1NzEsIm5iZiI6MTcyODk5MjI3MSwicGF0aCI6Ii8xNzQxODgxMjMvMzc2NTUxNzgyLTJkMTFlYjRlLWMwNWQtNGU0NC04ZGI3LWU5ZTE3ZWE4MjdkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxMTM3NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYTY5OGJhN2Y2MWI1YWE2YWJmN2RjYzk2MzY4Nzc0ZDNlYjlhYzRiNzY4NzBjNDdjOTdjN2E1MzgzNjNmZmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.KoWczZ4JfmaM98dSRqDp-pQsDLchCHmZcOoJNbP8j-s)
> 
> ## ✔️ Expected Behavior
> When dark mode is toggled, the "Stopwatch" page should switch to dark mode, matching the behavior of the other pages on the site.
> 
> ## ❌ Actual Behavior
> The "Stopwatch" page stays in light mode, even after dark mode is activated.

All the Best!!Give your best again @Saaarthak0102 .

**Comment by Saaarthak0102** [comment]
merged
