### ISSUE TITLE
[Bug]: Timer Lap Button Causes Page Scroll Lock on Homepage

### ISSUE THREAD

**Issue by pranusri1903** [param-code/counter-app#178]
# 🐞 Bug Report
## 📋 Description
When using the lap button on the timer in the homepage, the page scrolls down automatically, and the user is unable to scroll back up. This prevents access to the stop, reset, and further lap functionalities.

## ⚙️ Steps to Reproduce

Go to the homepage. Start the timer. Click the "Lap" button.

The page scrolls down and gets stuck, it basically freezes to a certain popint, preventing access to the timer controls (stop, reset, lap).

## ✔️ Expected Behavior
After using the lap button, the page should remain in place, allowing the user to continue interacting with the timer controls (stop, reset, lap).

## ❌ Actual Behavior
The page scrolls down automatically when the lap button is clicked, and the user cannot scroll back up to access the timer controls.

## 🔧 Additional Information
This issue occurs consistently when the lap button is clicked, making it impossible to control the timer further.

**Comment by pranusri1903** [comment]
@param-code  Please assign the issue to to me with the tags of gssoc, hacktober fest and the level which you see fit for the bug.

**Comment by param-code** [comment]
> ### 🐞 Bug Report
> ## 📋 Description
> When using the lap button on the timer in the homepage, the page scrolls down automatically, and the user is unable to scroll back up. This prevents access to the stop, reset, and further lap functionalities.
> 
> ## ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> Go to the homepage. Start the timer. Click the "Lap" button.
> 
> The page scrolls down and gets stuck, it basically freezes to a certain popint, preventing access to the timer controls (stop, reset, lap).
> 
> ## ✔️ Expected Behavior
> After using the lap button, the page should remain in place, allowing the user to continue interacting with the timer controls (stop, reset, lap).
> 
> ## ❌ Actual Behavior
> The page scrolls down automatically when the lap button is clicked, and the user cannot scroll back up to access the timer controls.
> 
> ## 🔧 Additional Information
> This issue occurs consistently when the lap button is clicked, making it impossible to control the timer further.

I am assigning this issue to you.All the Best @pranusri1903 .

**Comment by pranusri1903** [comment]
Hy, I see this issue has already been resolved by someone although I was the one asssigned to it.
I found another bug with the same 
I have raised the issue for it 
Issue number : #226
