### ISSUE TITLE
[Bug]: Incorrect Lap Time Calculation

### ISSUE THREAD

**Issue by IkkiOcean** [param-code/counter-app#188]
# 🐞 Bug Report

### 📋 Description
The application is not calculating lap records correctly when recording lap times. Instead of logging individual lap durations, it records the total elapsed time, leading to inaccurate analysis and visualization of lap data.

### ⚙️ Steps to Reproduce
1. Start the timer in the application.
2. Record multiple laps using the lap button.
3. Observe the recorded lap times in the lap analysis section.

### ✔️ Expected Behavior
Each lap should be recorded with its individual duration, allowing for accurate analysis of lap times.

### ❌ Actual Behavior
The application records the total elapsed time instead of separate lap durations, resulting in incorrect lap analysis and visualization.

### 📷 Screenshots

https://github.com/user-attachments/assets/aa98b7a2-171f-43f0-9ebf-f8fa7a39f9e1

### 🖥️ Environment (if applicable):
- **OS**: Windows, macOS
- **Browser**: Chrome, Safari

### 🔧 Additional Information
This bug significantly affects the analysis features of the application, making it difficult for users to track their performance accurately.

**Comment by IkkiOcean** [comment]
@param-code please assign it soon

**Comment by IkkiOcean** [comment]
@param-code hey param. I found a new and more problematic bug in the application  while solving this issue. The problem is the counter of this application is NOT updating with time and the counter is pretty much static. I found the component which is causing this problem and its the particle effect you have running on the page. The effect keeps re-rendering the page which leads to memory overload and issues in rendering much important component of the page which is the counter.


https://github.com/user-attachments/assets/3d9d9fa3-88a4-4fee-b213-0b1f3401cc30

- As of now I would recommend removing this component from the page

https://github.com/user-attachments/assets/a7944feb-30f2-4849-9daa-b1c1cd746147


So what should I do? should I remove it or I just pr what my issue was about

**Comment by param-code** [comment]
> @param-code hey param. I found a new and more problematic bug in the application while solving this issue. The problem is the counter of this application is NOT updating with time and the counter is pretty much static. I found the component which is causing this problem and its the particle effect you have running on the page. The effect keeps re-rendering the page which leads to memory overload and issues in rendering much important component of the page which is the counter.
> 
>  render.mp4 
> * As of now I would recommend removing this component from the page
> 
>  Screen.Recording.2024-10-18.at.7.09.15.PM.mov 
> So what should I do? should I remove it or I just pr what my issue was about

Remove it if you think it will solve the issue.
