### ISSUE TITLE
Add Multi-Language Support Using Language Translator

### ISSUE THREAD

**Issue by TBorundia** [param-code/counter-app#189]
# 🚀 Feature Request

### 📝 Feature Description
Implement a language translation API to allow dynamic switching between multiple languages.
Add a language selector (dropdown or buttons) to the UI for easy language switching.

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> Implement a language translation API to allow dynamic switching between multiple languages. Add a language selector (dropdown or buttons) to the UI for easy language switching.

Isn't it already there??

**Comment by param-code** [comment]
> i work on it if this issue is open

this issue had already been resolved @BhavikaPachauri .
