### ISSUE TITLE
Adding feedback form 

### ISSUE THREAD

**Issue by TBorundia** [param-code/counter-app#190]
# 🚀 Feature Request

### 📝 Feature Description
Create a feedback form to collect user input and improve website features. The form should include the following:

Input fields for name, email, and feedback message.
A star rating system for user satisfaction.
Form validation to ensure all fields are correctly filled before submission.
A responsive design that works seamlessly on all devices.
A success/failure message after form submission.

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> Create a feedback form to collect user input and improve website features. The form should include the following:
> 
> Input fields for name, email, and feedback message. A star rating system for user satisfaction. Form validation to ensure all fields are correctly filled before submission. A responsive design that works seamlessly on all devices. A success/failure message after form submission.

Good idea.You can also use the [backend](https://counter-app-backend.vercel.app/) to store the form
