### ISSUE TITLE
[Feature]: Adding input validations

### ISSUE THREAD

**Issue by Gauravtb2253** [param-code/counter-app#196]
# 🚀 Feature Request

### 📝 Feature Description
Hello I would like to add proper input form validations to the login and signup pages

### 🔧 How Will This Enhance the App?
Input validations helps to send valid data to the backend

Pls assign me

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> Hello I would like to add proper input form validations to the login and signup pages
> 
> ### 🔧 How Will This Enhance the App?
> Input validations helps to send valid data to the backend
> 
> Pls assign me

Okay.
