### ISSUE TITLE
Improve UI Design and Make Website Responsive

### ISSUE THREAD

**Issue by HarshitShukla-dev** [param-code/counter-app#2]
Hi,
I would like to suggest some UI improvements to enhance the overall look of the website and make it more visually appealing. I aim to ensure that the website follows a consistent design pattern throughout for a unified user experience. Additionally, I'll work on making the website responsive so that it adjusts seamlessly across multiple display sizes (mobile, tablet, desktop).

Proposed changes:
  1. Improve the layout and design to enhance user experience and maintain a single design pattern.
  2. Optimize the CSS to ensure responsiveness for various screen sizes.
  3. Test across multiple devices to verify smooth performance.

Could you please assign this issue to me? Let me know your thoughts or any specific design preferences!

Thank you!

**Comment by param-code** [comment]
Feel free to make the changes I have assigned this issue to you.Hoping to see some improvements by you.All the Best!!

**Comment by HarshitShukla-dev** [comment]
Hey @param-code, it'll be very great if you just assign my contribution a level as well.

**Comment by param-code** [comment]
> Hey @param-code, it'll be very great if you just assign my contribution a level as well.

Sorry!! I forgot to mention that
