### ISSUE TITLE
[Feature]: Google SignIN

### ISSUE THREAD

**Issue by pushkardev123** [param-code/counter-app#206]
# 🚀 Feature Request

### 📝 Feature Description
Adding Google Sign IN to make sign in/sign up process easier.

assign me this issue under gssoc and hacktoberfest label.

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> Adding Google Sign IN to make sign in/sign up process easier.
> 
> assign me this issue under gssoc and hacktoberfest label.

Sure.All the Best!!
