### ISSUE TITLE
Theme toggle icon is not working  other than home page

### ISSUE THREAD

**Issue by shivamy009** [param-code/counter-app#21]
![Screenshot 2024-10-02 175205](https://github.com/user-attachments/assets/e051a28c-cc22-4f61-acd4-6a1a68d7a3e8)
fix issue related to Theme toggle icon is not working  other than home page.

Please assign me to fix this.

**Comment by neeraj03788** [comment]
@param-code I want to conrtibute to the code base with clean and optimize code could you kindly assign me this.

**Comment by param-code** [comment]
> @param-code I want to conrtibute to the code base with clean and optimize code could you kindly assign me this.

yeah sure.There you go.I have assigned this to you as you have asked.All the Best!!
