### ISSUE TITLE
[Feature]: Convert images to webp format

### ISSUE THREAD

**Issue by Gauravtb2253** [param-code/counter-app#213]
# 🚀 Feature Request

### 📝 Feature Description
I would like to change images to webp format

### 🔧 How Will This Enhance the App?
Webp images are faster to load and offer optimization

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> I would like to change images to webp format
> 
> ### 🔧 How Will This Enhance the App?
> Webp images are faster to load and offer optimization

Okay.

**Comment by Gauravtb2253** [comment]
Can you pls add level 2 label

**Comment by param-code** [comment]
> Can you pls add level 2 label

will see later.
