### ISSUE TITLE
[Feature]: Add About Us Page

### ISSUE THREAD

**Issue by Sivasaiklu** [param-code/counter-app#216]
🚀 Feature Request: Add About Us Page
📝 Feature Description
A new "About Us" page that provides information about the app's purpose, mission, and the team behind it. This page will enhance transparency and credibility by giving users insight into the application's background and goals.

🔧 How Will This Enhance the App?
The "About Us" page will improve the user experience by:

Offering users a better understanding of the app's objectives and mission.
Highlighting the team behind the development of the app, fostering a sense of trust and connection.
Providing additional context to new users about what makes the app unique and valuable.
🎯 Use Cases
New Users: Gain a clearer idea of the app's purpose and team background.
Existing Users: Learn more about updates and the vision behind the app.
Potential Partners or Contributors: Understand the team's mission and decide to support or collaborate.
📦 Suggested Implementation
The page could include sections like:
App's mission and vision.
Overview of key features and goals.
Profiles or details of the team or contributors.
Any relevant milestones or achievements.
A visually appealing layout, possibly including images, team profiles, and a timeline of achievements.
📸 Additional Context
Include relevant design elements like team pictures, app logo, and branding.
Incorporate sections for "Our Story" or "Why We Built This App."
An optional CTA (Call to Action) for users interested in contributing to the project or providing feedback.

**Comment by param-code** [comment]
It's already there in the i button present in the navbar.
