### ISSUE TITLE
Implementing Lap Time Functionality in Counter App!

### ISSUE THREAD

**Issue by Ishratnoori** [param-code/counter-app#217]
Hi @param-code,

I would like to request to be assigned the issue related to "implementing the Lap Time functionality" in the Counter App. 
This feature will enhance the user experience by allowing users to record multiple intervals during their timing sessions.
I am excited to contribute to this and look forward to your approval.

(Please assign me under gssoc-ext and hacktoberfest :) )
Thank you!

Best regards,
Ishrat noori :)

**Comment by param-code** [comment]
It's is already there.
