### ISSUE TITLE
Change the logo

### ISSUE THREAD

**Issue by NK-Works** [param-code/counter-app#22]
![image](https://github.com/user-attachments/assets/acf17f5b-c6cd-4b9d-8999-947c27d374cf)

I want to change this logo and make it better...
Assign to me please...
make sure to add the labels...
Thanks...

**Comment by param-code** [comment]
> ![image](https://private-user-images.githubusercontent.com/132702983/372873607-acf17f5b-c6cd-4b9d-8999-947c27d374cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4OTE5MTMsIm5iZiI6MTcyNzg5MTYxMywicGF0aCI6Ii8xMzI3MDI5ODMvMzcyODczNjA3LWFjZjE3ZjViLWM2Y2QtNGI5ZC04OTk5LTk0N2MyN2QzNzRjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQxNzUzMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MTQ2YzUwYTU2ZTE0MjRhYTkxOWFhMzRmMDYxZjM0OWY2MTZlZTcyYzRjMGRhNjE1YWViNmFmM2EzYTVhMjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8xCVVnoS3vojXyVT8syhmg2UJcI0KSF2O8skr5SyEHs)
> 
> I want to change this logo and make it better... Assign to me please... make sure to add the labels... Thanks...

Sure do what you want to and let the world see it.All the Best!!
