### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [param-code/counter-app#220]
# 🚀 Feature Request

### 📝 Feature Description
i want to implement a 3D hover effect on a clock icon to enhance the footer, add underline animation on hover to navigation items, and align all sections in the footer with justified spacing, 

 

### 🔧 How Will This Enhance the App?
Enhancing the readability of your website will improve the user experience and help grab their attention.

### 🎯 Use Cases

It will enhance your readability, the overall website, and interaction with users.
 

### 📸 Additional Context
 
![a footer](https://github.com/user-attachments/assets/60a15cdc-c657-401a-9e9a-ca9afe64b1ef)

**Comment by param-code** [comment]
Okay.All the Best @biswajit-sarkar-007 .
