### ISSUE TITLE
[Bug]: Minor issue in WorkTracker dark theme

### ISSUE THREAD

**Issue by Saaarthak0102** [param-code/counter-app#222]
# 🐞 Bug Report

### 📋 Description
Some field titles are still in grey color even tho i fixed it earlier :

- Subject
- Set Time (in minutes)
- Set Time (in seconds)

### 📷 Screenshots
![image](https://github.com/user-attachments/assets/4819a45a-13e8-4bd6-946a-63b96edf2e23)

**Comment by param-code** [comment]
you can fix this issue but i won't provide any level.

**Comment by Saaarthak0102** [comment]
OK WILL FIX THIS in issue #223
