### ISSUE TITLE
[Custom]: Adding Contributors Icon on Navbar

### ISSUE THREAD

**Issue by Saaarthak0102** [param-code/counter-app#223]
# 💡 Custom Issue

## Description:
The navigation bar currently lacks a symbol for the "Our Contributors" page. To maintain consistency and improve navigation, a contributors' icon/logo should be added to the navbar.

## Steps to Implement:
Design a contributors' symbol/logo that matches the existing icons in the navbar (like the stopwatch, globe, etc.).
Add the symbol/logo to the navbar with a link to the "Our Contributors" page.
Ensure the icon's size, color, and design are consistent with the existing symbols.

## Expected Outcome:
A contributors' icon will appear in the navbar, improving user experience by allowing easy navigation to the Contributors page.

## Additional Information:
The icon should follow the same style as other symbols, using a minimalistic design and matching the color scheme of the navbar.

**Comment by param-code** [comment]
> # 💡 Custom Issue
> ## Description:
> The navigation bar currently lacks a symbol for the "Our Contributors" page. To maintain consistency and improve navigation, a contributors' icon/logo should be added to the navbar.
> 
> ## Steps to Implement:
> Design a contributors' symbol/logo that matches the existing icons in the navbar (like the stopwatch, globe, etc.). Add the symbol/logo to the navbar with a link to the "Our Contributors" page. Ensure the icon's size, color, and design are consistent with the existing symbols.
> 
> ## Expected Outcome:
> A contributors' icon will appear in the navbar, improving user experience by allowing easy navigation to the Contributors page.
> 
> ## Additional Information:
> The icon should follow the same style as other symbols, using a minimalistic design and matching the color scheme of the navbar.

Well you can make a list of all the issues first and then create issue.

**Comment by Saaarthak0102** [comment]
Ahh I just open the website and find a new one everyday 😅....thanks for assigning!
