### ISSUE TITLE
Want to add multiper Theme

### ISSUE THREAD

**Issue by mr-kunal-07** [param-code/counter-app#23]
hey @sanjay-kv 
In app there in only two theme LIGHT and DARK  
I want to add more theme for better user-Interface 
plz let me do this

**Comment by param-code** [comment]
> hey @sanjay-kv In app there in only two theme LIGHT and DARK I want to add more theme for better user-Interface plz let me do this

Move forward with your crazy Ideas.All the Best!!

**Comment by mr-kunal-07** [comment]
thank you so much
