### ISSUE TITLE
[Feature]: We can add a Privacy & Policy link in the footer section

### ISSUE THREAD

**Issue by TanmayKalra09** [param-code/counter-app#231]
# 🚀 Feature Request

### 📝 Feature Description
we are committed to protecting your personal information. This policy outlines how we collect, use, and safeguard your data; on clicking the link it will direct to dedicated Privacy and Policy page.

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> we are committed to protecting your personal information. This policy outlines how we collect, use, and safeguard your data; on clicking the link it will direct to dedicated Privacy and Policy page.

Sure.
