### ISSUE TITLE
[Feature]: Add the MIT License

### ISSUE THREAD

**Issue by Dipanita45** [param-code/counter-app#232]
# 🚀 Feature Request

### 📝 Feature Description
<-- Adding the MIT license -->

### 🔧 How Will This Enhance the App?
<-- Protect the project from causing damage -->

### 📦 Suggested Implementation
<-- Enhance the website-->

Please assign me the issue
@param-code

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> <-- Adding the MIT license -->
> 
> ### 🔧 How Will This Enhance the App?
> <-- Protect the project from causing damage -->
> 
> ### 📦 Suggested Implementation
> <-- Enhance the website-->
> 
> Please assign me the issue @param-code

Okay.let's see.
