### ISSUE TITLE
[Feature]: Improvement in About Page of Counter App 

### ISSUE THREAD

**Issue by Ashwinib26** [param-code/counter-app#240]
# 🚀 Feature Request : **Improvements in About Page**

### 📝 Feature Description
Here , this page can be improved by following updates :
1. Hover effect on 4 **box cards** on the right side in Initial part of about page.
2. Customizing and redesigning app info in '**About Counter Clock**' section.
3. Beautification of '**Our Features**' section.
4. User should get a notification once they have subscribed the newsletter in '**Get in Touch**' section.
5. Adding '**Testimonials**' section in About page where experience and review of users will appear in slidable cards format.

### 🔧 How Will This Enhance the App?
These updates will enhance user engagement and interactivity, making the website more visually appealing and user-friendly. Improved sections and review mechanisms will increase user satisfaction and provide a more polished experience.

### 🎯 Use Cases
1. Increased User Engagement
2. Improved User Experience

### 📦 Suggested Implementation

These are the areas I want to work upon : 

![Screenshot 2024-10-22 180457](https://github.com/user-attachments/assets/4cd73109-694f-4111-b7b1-43368f5b39e2)
![Screenshot 2024-10-22 180419](https://github.com/user-attachments/assets/29d7130e-010a-4af1-92e0-a7946f3776bb)
![Screenshot 2024-10-22 180431](https://github.com/user-attachments/assets/fa4545cf-92f9-4a24-afe2-d4295e81d8f8)
![Screenshot 2024-10-22 180457](https://github.com/user-attachments/assets/a539ea8d-c4f8-4397-ba04-f3bb0352a8d6)

**Comment by param-code** [comment]
> # 🚀 Feature Request : **Improvements in About Page**
> ### 📝 Feature Description
> Here , this page can be improved by following updates :
> 
> 1. Hover effect on 4 **box cards** on the right side in Initial part of about page.
> 2. Customizing and redesigning app info in '**About Counter Clock**' section.
> 3. Beautification of '**Our Features**' section.
> 4. User should get a notification once they have subscribed the newsletter in '**Get in Touch**' section.
> 5. Adding '**Testimonials**' section in About page where experience and review of users will appear in slidable cards format.
> 
> ### 🔧 How Will This Enhance the App?
> These updates will enhance user engagement and interactivity, making the website more visually appealing and user-friendly. Improved sections and review mechanisms will increase user satisfaction and provide a more polished experience.
> 
> ### 🎯 Use Cases
> 1. Increased User Engagement
> 2. Improved User Experience
> 
> ### 📦 Suggested Implementation
> These are the areas I want to work upon :
> 
> ![Screenshot 2024-10-22 180457](https://private-user-images.githubusercontent.com/149402720/378840029-4cd73109-694f-4111-b7b1-43368f5b39e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTU0NTgsIm5iZiI6MTcyOTY5NTE1OCwicGF0aCI6Ii8xNDk0MDI3MjAvMzc4ODQwMDI5LTRjZDczMTA5LTY5NGYtNDExMS1iN2IxLTQzMzY4ZjViMzllMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxNDUyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMmUxZDIxYWQ4MjJkODBmZmQ2N2ZhY2RmOTY3MGVlNWFiMTQ1YzVhOGUxMmJiY2IzMDNlOWE0Y2JjMjg0NmM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.oZwtLSbN-k7FAiQvy5jgWKB9VxwGM623VW-A9WhCK5w) ![Screenshot 2024-10-22 180419](https://private-user-images.githubusercontent.com/149402720/378840276-29d7130e-010a-4af1-92e0-a7946f3776bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTU0NTgsIm5iZiI6MTcyOTY5NTE1OCwicGF0aCI6Ii8xNDk0MDI3MjAvMzc4ODQwMjc2LTI5ZDcxMzBlLTAxMGEtNGFmMS05MmUwLWE3OTQ2ZjM3NzZiYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxNDUyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZTJmNjZlOTA0YTIzMjIyNjQ2MGViMDYxYmEzNTg1ZmFmYWJiYWM0YTRkN2FiN2Q5NTJlZTFjOWZlYjI2YWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2xGB9g0KfQ1hbTo-O9nd6v54coBLV-6twSuxTcymzS4) ![Screenshot 2024-10-22 180431](https://private-user-images.githubusercontent.com/149402720/378840343-fa4545cf-92f9-4a24-afe2-d4295e81d8f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTU0NTgsIm5iZiI6MTcyOTY5NTE1OCwicGF0aCI6Ii8xNDk0MDI3MjAvMzc4ODQwMzQzLWZhNDU0NWNmLTkyZjktNGEyNC1hZmUyLWQ0Mjk1ZTgxZDhmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxNDUyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDg4MTZkMDk4ZTFkZmY2YzQ0Mjg2MzQ0MTkyMTlhMDkwZTIwMDc2MmUxODQ2NTEyNjc2ZjI3OGM0MDFkMzlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nPaU3IgxZSL3FW8pphXUKc3fGdPAcp_8zLazqeEYOQA) ![Screenshot 2024-10-22 180457](https://private-user-images.githubusercontent.com/149402720/378840392-a539ea8d-c4f8-4397-ba04-f3bb0352a8d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTU0NTgsIm5iZiI6MTcyOTY5NTE1OCwicGF0aCI6Ii8xNDk0MDI3MjAvMzc4ODQwMzkyLWE1MzllYThkLWM0ZjgtNDM5Ny1iYTA0LWYzYmIwMzUyYThkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxNDUyMzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMjU5M2EzOWU2MWFjYTZiYWIzYmQ0MDAzMzBjYmQ3MjNkNWVkMjYxNWJkNTk2NDc1YWYwODU2ZTkxMTY1MjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dhTu-bXBi6h1uVc63EOmP2hAgkiATBfV3kbnIguzUmE)

Sure.

**Comment by ambrishgoswami** [comment]
please assign this issue me

**Comment by Ashwinib26** [comment]
@param-code , Can I get level 2 label for all of these tasks , please ?

**Comment by Ashwinib26** [comment]
@param-code , there is error in latest project , kindly rectify.
When I done 'synk fork' and run the project it showed me the error.
