### ISSUE TITLE
[Feature]: Addition of a review cum RATE US section

### ISSUE THREAD

**Issue by SrishtiChamoli** [param-code/counter-app#241]
# 🚀 Feature Request

### 📝 Feature Description
We can add a review or rating section which takes in user input in the form of written feedbacks and star ratings

### 🔧 How Will This Enhance the App?
It will help us to work towards the direction of elevating the user experience

### 🎯 Use Cases
It will get us a database of user feedbacks and issues we have to focus upon in the future. It will also improve the user experience.

### 📦 Suggested Implementation
After 10 seconds of being on the home page, the user will get a pop up dialog box asking for the feedback of the user in terms of stars or comments.

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> We can add a review or rating section which takes in user input in the form of written feedbacks and star ratings
> 
> ### 🔧 How Will This Enhance the App?
> It will help us to work towards the direction of elevating the user experience
> 
> ### 🎯 Use Cases
> It will get us a database of user feedbacks and issues we have to focus upon in the future. It will also improve the user experience.
> 
> ### 📦 Suggested Implementation
> After 10 seconds of being on the home page, the user will get a pop up dialog box asking for the feedback of the user in terms of stars or comments.

Sure.
