### ISSUE TITLE
[Feature]: Add hoover effect on about counter 

### ISSUE THREAD

**Issue by Himanshu-kumar025** [param-code/counter-app#242]
### 📝 Feature Description
Add hover effect on the about counter card so It make website more engaging . I like to improve this card under GSSOC'24 and Hacktoofest'24
thank you 

![Screenshot 2024-10-22 185009](https://github.com/user-attachments/assets/37bf409a-ed95-4d6e-9760-c5fbd829fc46)

**Comment by param-code** [comment]
Someone else is already working on this.
