### ISSUE TITLE
[Custom]: Enhance the UI of the Signup and Login page

### ISSUE THREAD

**Issue by prasoonk1204** [param-code/counter-app#243]
# 💡 Custom Issue

### 📝 Description
I want to enhance the ui of the Signup and Login pages, make them more visually appealing and align them with the overall theme of the app

### 🔍 Steps to Reproduce (if applicable)
1. Change the colors and texts
2. Change the images
3. Modify the hover effect on the buttons
4. Align the elements in a better way

**Comment by param-code** [comment]
> # 💡 Custom Issue
> ### 📝 Description
> I want to enhance the ui of the Signup and Login pages, make them more visually appealing and align them with the overall theme of the app
> 
> ### 🔍 Steps to Reproduce (if applicable)
> 1. Change the colors and texts
> 2. Change the images
> 3. Modify the hover effect on the buttons
> 4. Align the elements in a better way
> 
> ### 🎯 Expected Outcome
> ### 📸 Screenshots or Additional Information

Sure @prasoonk1204 .
