### ISSUE TITLE
[Custom]: Upgradation of code of conduct.md file 

### ISSUE THREAD

**Issue by Nikhil0-3** [param-code/counter-app#245]
# 💡 There are two files of code of conduct 
I want to mak it single one and make little changes in it.

### 📝 Description

I want to add following points
Pledge
Standards
Enforcement Responsibilities
Scope
Pull Request Guidelines
Enforcement
Enforcement Guidelines
Attribution

I want to make your file like this
I attached the screenshot below

📸 Screenshots or Additional Information

![Screenshot 2024-10-22 204810](https://github.com/user-attachments/assets/40f73016-376b-4769-b365-6b2621381516)

![Screenshot 2024-10-22 204822](https://github.com/user-attachments/assets/6e77dc22-bc03-4e2b-bd13-744cfaa2ef75)
![Screenshot 2024-10-22 204906](https://github.com/user-attachments/assets/3907ca45-5be8-4a8b-8a5e-2222503631f2)
![Screenshot 2024-10-22 204918](https://github.com/user-attachments/assets/def1b438-6ffc-4dba-9c6f-ee8e07e50917)

**Comment by Nikhil0-3** [comment]
If possible please add the lables od level 2 or level 3, it will be a great help from your side.

**Comment by param-code** [comment]
> # 💡 There are two files of code of conduct
> I want to mak it single one and make little changes in it.
> 
> ### 📝 Description
> I want to add following points Pledge Standards Enforcement Responsibilities Scope Pull Request Guidelines Enforcement Enforcement Guidelines Attribution
> 
> I want to make your file like this I attached the screenshot below
> 
> 📸 Screenshots or Additional Information
> 
> ![Screenshot 2024-10-22 204810](https://private-user-images.githubusercontent.com/149102391/378911851-40f73016-376b-4769-b365-6b2621381516.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTU0NTIsIm5iZiI6MTcyOTY5NTE1MiwicGF0aCI6Ii8xNDkxMDIzOTEvMzc4OTExODUxLTQwZjczMDE2LTM3NmItNDc2OS1iMzY1LTZiMjYyMTM4MTUxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxNDUyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTVmN2YyZTQ2OTlmY2E3NzhjODZmNDQ2ZTM1ZWM0MGNkYzI4MWM2ZTg1MzY1NDNmMTRhMmMyYzMzYTFlYzc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nU-dqFqjjEdfUFTKiRCbw1FhJlNIwPVYNczv5g6dDNA)
> 
> ![Screenshot 2024-10-22 204822](https://private-user-images.githubusercontent.com/149102391/378911864-6e77dc22-bc03-4e2b-bd13-744cfaa2ef75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTU0NTIsIm5iZiI6MTcyOTY5NTE1MiwicGF0aCI6Ii8xNDkxMDIzOTEvMzc4OTExODY0LTZlNzdkYzIyLWJjMDMtNGUyYi1iZDEzLTc0NGNmYWEyZWY3NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxNDUyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZDY5MWU3NGFmNDQ2N2ExYmRkMDYzMDdkYTcwZjhiOTlmMzBmNTRlZWZjMmY5NWUzYWZhN2M2MWEzMzlhYjFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6L7uw61-OU3_1gz1zpm9jLm-kOWsD8j4gYAKtFuS554) ![Screenshot 2024-10-22 204906](https://private-user-images.githubusercontent.com/149102391/378911903-3907ca45-5be8-4a8b-8a5e-2222503631f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTU0NTIsIm5iZiI6MTcyOTY5NTE1MiwicGF0aCI6Ii8xNDkxMDIzOTEvMzc4OTExOTAzLTM5MDdjYTQ1LTViZTgtNGE4Yi04YTVlLTIyMjI1MDM2MzFmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxNDUyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjRlYThiZWZlNTRlNTExYmJiYzlmNzJmOGIwNWI3YzNmZWNiNmZkYzA4ZThiNzZjMDIxNmFjOGVhNzZiMTY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.eqik03vizUTY0WyfTjqbCFnxKPxWdYt18sjDmrQWQ-I) ![Screenshot 2024-10-22 204918](https://private-user-images.githubusercontent.com/149102391/378911959-def1b438-6ffc-4dba-9c6f-ee8e07e50917.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2OTU0NTIsIm5iZiI6MTcyOTY5NTE1MiwicGF0aCI6Ii8xNDkxMDIzOTEvMzc4OTExOTU5LWRlZjFiNDM4LTZmZmMtNGRiYS05YzZmLWVlOGUwN2U1MDkxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyM1QxNDUyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNTU2Nzg3MTc5NmNlMDZlMzZkMjM3MzU0YjVlYjhlMGUyYWMzMjA3ZDE3YjdhMzY1YzU5ODZmNzA2YjYwMGQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CdQwaPuoObdNkWvazy92lifWc1Yh0eWG1ma8YfoVt0k)

Sure.
