### ISSUE TITLE
[Feature]: No option to close the rate us section

### ISSUE THREAD

**Issue by AswaniBolisetti** [param-code/counter-app#269]
@param-code 
There is no option to close the rate us section, if user dont want to share the rating, then there is no option to close, they have to reload the website only
So I would like add a close button
Could you please assign it to me

**Comment by param-code** [comment]
> @param-code There is no option to close the rate us section, if user dont want to share the rating, then there is no option to close, they have to reload the website only So I would like add a close button Could you please assign it to me

Sure.
