### ISSUE TITLE
code of conduct

### ISSUE THREAD

**Issue by INam1995** [param-code/counter-app#27]
Hey @param-code 
I would like to work on the "Code of Conduct" issue. Please assign it to me under the gssoc-ext label.

**Comment by param-code** [comment]
> Hey @param-code I would like to work on the "Code of Conduct" issue. Please assign it to me under the gssoc-ext label.

Okay.Move ahead with your ideas.All the Best!!

**Comment by RanitDERIA** [comment]
I'd love to be assigned to issue #29   as I have the relevant experience in Web Dev and believe I can provide an efficient solution. Looking forward to contributing!
