### ISSUE TITLE
[Bug]: Signup with Google and apple feature 

### ISSUE THREAD

**Issue by manya1632** [param-code/counter-app#271]
# 🐞 Bug Report

### 📋 Description
the signup page is well built but when clicked on signup with google , the feature does not work neither does signup with apple does

### ⚙️ Steps to Reproduce
1. a third-party authentication service like Firebase Authentication or NextAuth.js for Next.js projects

### ✔️ Expected Behavior
Successful signup after a third party page opens

### ❌ Actual Behavior
Shows signup errors

@param-code please assign this task to me under hacktoberfest and gssoc  !

Checklist
✔️I have read the Contributing Guidelines
✔️I have read the Code Of Conduct
✔️The changes don't break the code

**Comment by param-code** [comment]
> # 🐞 Bug Report
> ### 📋 Description
> the signup page is well built but when clicked on signup with google , the feature does not work neither does signup with apple does
> 
> ### ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> 1. a third-party authentication service like Firebase Authentication or NextAuth.js for Next.js projects
> 
> ### ✔️ Expected Behavior
> Successful signup after a third party page opens
> 
> ### ❌ Actual Behavior
> Shows signup errors
> 
> @param-code please assign this task to me under hacktoberfest and gssoc !
> 
> Checklist ✔️I have read the Contributing Guidelines ✔️I have read the Code Of Conduct ✔️The changes don't break the code

Okay.I am assigning you this.All the Best @manya1632 .
