### ISSUE TITLE
[Bug]: Error in syntax in SignupForm.jsx & LoginForm.jsx files

### ISSUE THREAD

**Issue by akank1410** [param-code/counter-app#273]
# 🐞 Bug Report

### 📋 Description

the </form> and </div> tag in line ending not correct leading to error during npm run dev

### ⚙️ Steps to Reproduce
1.  correct the order of </form> and </div> tag as shared in the screen shot

### 📷 Screenshots

SignupForm.jsx

Actual code erro:
![12](https://github.com/user-attachments/assets/9f227426-85de-448b-870f-f19c88286be4)

Updated code:
![111](https://github.com/user-attachments/assets/6db9a5b2-09a9-4797-a91c-f530db0e2336)

LoginForm.jsx

Actual code erro:
![11](https://github.com/user-attachments/assets/084d6e2d-4b43-4225-9260-8669065fab76)

Updated code:
![31](https://github.com/user-attachments/assets/e418a3ea-29c2-4023-87b9-58df22085d38)

### 🖥️ Environment (if applicable):
- **OS**: (e.g., Windows, macOS, Linux)
- **Browser**: (e.g., Chrome, Safari, Firefox)
- **Version**: (if relevant)

### 🔧 Additional Information

Kindly assign me the issue under [gssoc-ext][hacktoberfest-accepted] tag.

**Comment by param-code** [comment]
> # 🐞 Bug Report
> ### 📋 Description
> the and tag in line ending not correct leading to error during npm run dev
> 
> ### ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> 1. correct the order of  and  tag as shared in the screen shot
> 
> ### ✔️ Expected Behavior
> ### ❌ Actual Behavior
> ### 📷 Screenshots
> SignupForm.jsx
> 
> Actual code erro: ![12](https://private-user-images.githubusercontent.com/54724406/380119495-9f227426-85de-448b-870f-f19c88286be4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MzUxODksIm5iZiI6MTcyOTkzNDg4OSwicGF0aCI6Ii81NDcyNDQwNi8zODAxMTk0OTUtOWYyMjc0MjYtODVkZS00NDhiLTg3MGYtZjE5Yzg4Mjg2YmU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA5MjgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNmNhMDc5ZjdlZTZhMTA3YmJjN2M0OWVhMzdkNmYyZjAzMGE5ZWRhNzgxMzY2Zjc0ODAyYmJkZWVjYmM3MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.763lTFZ0dkGsKn_eIYLr10GxIs6kjsVve0Ex397tL9s)
> 
> Updated code: ![111](https://private-user-images.githubusercontent.com/54724406/380120236-6db9a5b2-09a9-4797-a91c-f530db0e2336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MzUxODksIm5iZiI6MTcyOTkzNDg4OSwicGF0aCI6Ii81NDcyNDQwNi8zODAxMjAyMzYtNmRiOWE1YjItMDlhOS00Nzk3LWE5MWMtZjUzMGRiMGUyMzM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA5MjgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlODI0OTQzODJjMTdhZDJjOTkyZGVjYjg3YzQ2ZDc2NGQ2MWYwMjkwZDc0M2FjZGVmNjFhNmQxNWE2ZGVjMzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4SX0WjjN-YfbCcTXar58F3YznCDgk6fl4xJffOJBtoI)
> 
> LoginForm.jsx
> 
> Actual code erro: ![11](https://private-user-images.githubusercontent.com/54724406/380119043-084d6e2d-4b43-4225-9260-8669065fab76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MzUxODksIm5iZiI6MTcyOTkzNDg4OSwicGF0aCI6Ii81NDcyNDQwNi8zODAxMTkwNDMtMDg0ZDZlMmQtNGI0My00MjI1LTkyNjAtODY2OTA2NWZhYjc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA5MjgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjNWJlNzU2ZTE4MTJhMmZkNmM5OWU2NTViMjY0NzZmZmZkNmVkZmI1MTk4Y2VkNTVhNmYwNjM5OWViZTJkZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ksOf5mWKqjnkO01U-C4ZcnfRkJiL4WCxXpkn9ZAePzA)
> 
> Updated code: ![31](https://private-user-images.githubusercontent.com/54724406/380120734-e418a3ea-29c2-4023-87b9-58df22085d38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5MzUxODksIm5iZiI6MTcyOTkzNDg4OSwicGF0aCI6Ii81NDcyNDQwNi8zODAxMjA3MzQtZTQxOGEzZWEtMjljMi00MDIzLTg3YjktNThkZjIyMDg1ZDM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI2VDA5MjgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmYzEzMDljNjAxZWM4YmQyMGQ3YWJiOTY5NjdlM2YyZDk2ZWViNWM0YjA2NjRlNzA4ZTczMDUyMzQwYjViYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WQBM94qU8J5Uvh2PldvQCyI21H0t2kBNjrkBoN9s-qE)
> 
> ### 🖥️ Environment (if applicable):
> * **OS**: (e.g., Windows, macOS, Linux)
> * **Browser**: (e.g., Chrome, Safari, Firefox)
> * **Version**: (if relevant)
> 
> ### 🔧 Additional Information
> Kindly assign me the issue under [gssoc-ext][hacktoberfest-accepted] tag.

Sure.

**Comment by BhavikaPachauri** [comment]
can i work on it if this issue is open

**Comment by akank1410** [comment]
I am working on it

**Comment by param-code** [comment]
> I am working on it

It's been so long

**Comment by akank1410** [comment]
i have the solution. Will commit it today

**Comment by akank1410** [comment]
is it fine

**Comment by akank1410** [comment]
the issue is still not fixed
