### ISSUE TITLE
[Feature]: Enhance privacy policy

### ISSUE THREAD

**Issue by AswaniBolisetti** [param-code/counter-app#292]
@param-code 
Privacy policy page is not aligning with the website styling
I would like to make it align with the website styling and also it lacks navbar
Could you please assign it to me

https://github.com/user-attachments/assets/9459b8f5-1728-47e5-ae12-1cd96eea9544

**Comment by param-code** [comment]
I think you should first make a complete list of issues create it.You shouldn't create this many issues.
