### ISSUE TITLE
Add animated cursor along with animated background 

### ISSUE THREAD

**Issue by manya1632** [param-code/counter-app#3]
I will add a dark bg and a light color cursor with animation 

Checklist
 - I have checked the existing issues.
 - I have read the Contributing Guidelines
 - I have read the Code Of Conduct
 - The changes don't break the code

Assign it to me @param-code

**Comment by param-code** [comment]
move ahead with your creativity . All the Best!!

**Comment by manya1632** [comment]
https://github.com/user-attachments/assets/00e6c60b-4675-4fd5-a58f-4da1ebf1eae2

Please review if I should make this change or not, and kindly suggest any changes you want.

**Comment by manya1632** [comment]
Uploading Screen Recording 2024-10-05 190723.mp4…

take a look at the dark mode. Suggest any changes. 

Hey @param-code can you include hacktoberfest2024 tag so that it can be considered there too.

**Comment by param-code** [comment]
> Untitled.video.-.Made.with.Clipchamp.1.mp4 
> Please review if I should make this change or not, and kindly suggest any changes you want.

this one looks great , can you change the color of the header as well ??

**Comment by param-code** [comment]
> Screen.Recording.2024-10-05.190723.mp4 
> take a look at the dark mode. Suggest any changes.
> 
> Hey @param-code can you include hacktoberfest2024 tag so that it can be considered there too.

Nice!!

**Comment by manya1632** [comment]
Thank you !!
