### ISSUE TITLE
[Bug]: In Login page the password eye toggle button does not work properly.

### ISSUE THREAD

**Issue by antan2002** [param-code/counter-app#309]
# 🐞 Bug Report

### 📋 Description
In Login page the password eye toggle button does not work properly.

### ⚙️ Steps to Reproduce
1.  put password
2. click on the eye button 
3. password is not shown

### ✔️ Expected Behavior
when the toggle button will be clicked , password should be shown.

### ❌ Actual Behavior
In Login page the password eye toggle button does not work properly.

### 🔧 Additional Information
please assign me , i want to fix the bug.

**Comment by antan2002** [comment]
![Uploading Screenshot (54).png…]()

**Comment by param-code** [comment]
> # 🐞 Bug Report
> ### 📋 Description
> In Login page the password eye toggle button does not work properly.
> 
> ### ⚙️ Steps to Reproduce
> Steps to reproduce the behavior:
> 
> 1. put password
> 2. click on the eye button
> 3. password is not shown
> 
> ### ✔️ Expected Behavior
> when the toggle button will be clicked , password should be shown.
> 
> ### ❌ Actual Behavior
> In Login page the password eye toggle button does not work properly.
> 
> ### 📷 Screenshots
> ### 🔧 Additional Information
> please assign me , i want to fix the bug.

Okay.
