### ISSUE TITLE
[Feature]: Add Contact Us Via E-Mail

### ISSUE THREAD

**Issue by PriyanshuValiya** [param-code/counter-app#311]
# 🚀 Feature Request

### 📝 Feature Description
From this page, user can mail their issue, reviews, and queries directly from the website.

### 📸 Previous Work
![Screenshot 2024-10-25 125504](https://github.com/user-attachments/assets/a1c0232e-28c2-43be-a5df-2c96f4244fb6)

**Comment by param-code** [comment]
this issue has already been resolved via the feedback section.
