### ISSUE TITLE
Enhance UI and Styling of Privacy and Policy page

### ISSUE THREAD

**Issue by T-Fathima** [param-code/counter-app#312]
# 🚀 Feature Request

![image](https://github.com/user-attachments/assets/196ed872-6277-4211-8f3c-1bd287a8ab66)

### 📝 Feature Description
The current UI of the privacy policy page can be improved to enhance user experience and visual appeal. I propose making the following enhancements:

Modernize the color scheme: Use a more visually appealing palette to improve readability and aesthetics.
Refine typography: Improve font choices and sizes for better readability and a polished look.
Enhance component styling: Style buttons, forms, and navigation components to align with modern design standards.
Responsive design: Ensure the UI is fully responsive and optimized for different screen sizes, including mobile and tablet.

### 🔧 How Will This Enhance the App?
A cleaner, more modern interface that improves user interaction.
Enhanced consistency in design and better responsiveness across devices.

### 📸 Additional Context
I would like to work on it.
@param-code Please assign it to me under gssoc-ext level2 and hacktoberfest.

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ![image](https://private-user-images.githubusercontent.com/148070120/381506961-196ed872-6277-4211-8f3c-1bd287a8ab66.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyODgzMzAsIm5iZiI6MTczMDI4ODAzMCwicGF0aCI6Ii8xNDgwNzAxMjAvMzgxNTA2OTYxLTE5NmVkODcyLTYyNzctNDIxMS04ZjNjLTFiZDI4N2E4YWI2Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAzMFQxMTMzNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjhiMzFmNmM1NjlmNzQyOWRhNjNkOGY5MTVmZGQ1YmYwMGJmYjYzMDhhZDM2YzM5ODgzOTYxZjVkYWUxMGUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5dvl0-1CZVcw02HzBTxIhtMAXIZttW-_kDwsi5-mxs8)
> 
> ### 📝 Feature Description
> The current UI of the privacy policy page can be improved to enhance user experience and visual appeal. I propose making the following enhancements:
> 
> Modernize the color scheme: Use a more visually appealing palette to improve readability and aesthetics. Refine typography: Improve font choices and sizes for better readability and a polished look. Enhance component styling: Style buttons, forms, and navigation components to align with modern design standards. Responsive design: Ensure the UI is fully responsive and optimized for different screen sizes, including mobile and tablet.
> 
> ### 🔧 How Will This Enhance the App?
> A cleaner, more modern interface that improves user interaction. Enhanced consistency in design and better responsiveness across devices.
> 
> ### 📸 Additional Context
> I would like to work on it. @param-code Please assign it to me under gssoc-ext level2 and hacktoberfest.

Sure.Let's see what you can do.
