### ISSUE TITLE
[Feature]: Improve UI of feedback page

### ISSUE THREAD

**Issue by Gauravtb2253** [param-code/counter-app#314]
# 🚀 Feature Request

### 📝 Feature Description
I would like to improve the UI of feedback page
Pls assign me
I will also add input validations to the form fields of feedback form

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> I would like to improve the UI of feedback page Pls assign me I will also add input validations to the form fields of feedback form

Okay @Gauravtb2253 .

**Comment by rajneeshverma1** [comment]
@param-code i assign the labels, you can start working
