### ISSUE TITLE
[Feature]: Rate us Implementation

### ISSUE THREAD

**Issue by haseebzaki-07** [param-code/counter-app#319]
# 🚀 Feature Request

### 📝 Feature Description
users submitting their ratings should be either stored in the database or a copy of their ratings should be sent to their valid mail ids saying "thank you for rating us!"

### 🔧 How Will This Enhance the App?
Enhancing the user experience on the website.

![Screenshot 2024-10-31 122655](https://github.com/user-attachments/assets/4c0a4ab5-1cc1-4909-8a69-d3299bc30dac)

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> users submitting their ratings should be either stored in the database or a copy of their ratings should be sent to their valid mail ids saying "thank you for rating us!"
> 
> ### 🔧 How Will This Enhance the App?
> Enhancing the user experience on the website.
> 
> ![Screenshot 2024-10-31 122655](https://private-user-images.githubusercontent.com/147314463/381855421-4c0a4ab5-1cc1-4909-8a69-d3299bc30dac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NjEyMDAsIm5iZiI6MTczMDQ2MDkwMCwicGF0aCI6Ii8xNDczMTQ0NjMvMzgxODU1NDIxLTRjMGE0YWI1LTFjYzEtNDkwOS04YTY5LWQzMjk5YmMzMGRhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwMVQxMTM1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNTQ0YWVlOThlZmIxZTQwNDIxNWJiY2IxNjBhYzZhMWQ3M2NjNmY3ZmIwNTU3MmI5Njc1NTgxMzAxNGU3YzE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2JLj8jiha67bnCupTyUshbgobChChEmFyhAKuxyB2fg)

It's already implemented in the feedback.
