### ISSUE TITLE
[Feature]: SIgnup with google

### ISSUE THREAD

**Issue by haseebzaki-07** [param-code/counter-app#320]
# 🚀 Feature Request

### 📝 Feature Description
Adding google signup so that users can signup the website directly with google.

### 🔧 How Will This Enhance the App?
since the frontend is there, I want to integrate its backend and complete functioning.

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> Adding google signup so that users can signup the website directly with google.
> 
> ### 🔧 How Will This Enhance the App?
> since the frontend is there, I want to integrate its backend and complete functioning.
> 
> ### 🎯 Use Cases
> ### 📦 Suggested Implementation
> ### 📸 Additional Context

Okay.All the Best!!
