### ISSUE TITLE
[Feature]: Add newsletter implementation

### ISSUE THREAD

**Issue by haseebzaki-07** [param-code/counter-app#321]
# 🚀 Feature Request

### 📝 Feature Description
Users entering their valid mail ids in the stay updated section should receive a confirmation mail to their mail ids.
I want to write the backend and integrate to the frontend with toasts for handling success and failures.

### 🎯 Use Cases
Important to roll out future updates to the customers, possible only when they are subscribed to the platform.

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> Users entering their valid mail ids in the stay updated section should receive a confirmation mail to their mail ids. I want to write the backend and integrate to the frontend with toasts for handling success and failures.
> 
> ### 🔧 How Will This Enhance the App?
> ### 🎯 Use Cases
> Important to roll out future updates to the customers, possible only when they are subscribed to the platform.
> 
> ### 📦 Suggested Implementation
> ### 📸 Additional Context

Okay.
