### ISSUE TITLE
[Feature]: Rearranging files for code readability

### ISSUE THREAD

**Issue by Gauravtb2253** [param-code/counter-app#322]
# 🚀 Feature Request

### 📝 Feature Description
Currently in the controller folder of backend, all the controllers and routes are in single file
I would like to separate it as per usage
It will increase the code readability and it is a good practice to separate things

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> Currently in the controller folder of backend, all the controllers and routes are in single file I would like to separate it as per usage It will increase the code readability and it is a good practice to separate things

Okay.
