### ISSUE TITLE
[Feature]: Add Visitor Count to Footer ✨

### ISSUE THREAD

**Issue by AnushkaChouhan25** [param-code/counter-app#333]
# 🚀 Feature Request

### 📝 Feature Description

Implement a visitor count feature in the footer to display the total number of users who have visited the website. This will provide users with a sense of community and engagement, encouraging them to explore the site further.

**Comment by param-code** [comment]
> # 🚀 Feature Request
> ### 📝 Feature Description
> Implement a visitor count feature in the footer to display the total number of users who have visited the website. This will provide users with a sense of community and engagement, encouraging them to explore the site further.
> 
> ### 🔧 How Will This Enhance the App?
> ### 🎯 Use Cases
> ### 📦 Suggested Implementation
> ### 📸 Additional Context

Sure.I am assigning this to you @AnushkaChouhan25 .All the Best!!

**Comment by AnushkaChouhan25** [comment]
Hey @param-code, Can you please assign this issue under level 3, if you see other projects this issue is assigned under level 3.
