### ISSUE TITLE
[Custom]: the subscribe to newsletter option is not storing email for future purpose.

### ISSUE THREAD

**Issue by VinayLodhi1712** [param-code/counter-app#335]
# 💡 Custom Issue

### 📝 Description
The email in subscribe to newsletter option is not storing in database so if someone with one email id can subscribed with more than one time. So what i can do is the i can store the emails.

### 🔍 Steps to Reproduce (if applicable)
1. Go to newsletter and try one email with many times

### 🎯 Expected Outcome
1. store the emails so that with one email cant be subscribed many times.
2. if in future if we want to send updates to the user then we have that emails stored in out database. so we can send the updates to the user via email.

**Comment by param-code** [comment]
> # 💡 Custom Issue
> ### 📝 Description
> The email in subscribe to newsletter option is not storing in database so if someone with one email id can subscribed with more than one time. So what i can do is the i can store the emails.
> 
> ### 🔍 Steps to Reproduce (if applicable)
> 1. Go to newsletter and try one email with many times
> 
> ### 🎯 Expected Outcome
> 1. store the emails so that with one email cant be subscribed many times.
> 2. if in future if we want to send updates to the user then we have that emails stored in out database. so we can send the updates to the user via email.
> 
> ### 📸 Screenshots or Additional Information

Okay.I am assigning this to you @VinayLodhi1712 .

**Comment by VinayLodhi1712** [comment]
ok thankyou sir @param-code but can you increase its level as it is a backend + database issue i am doing so plz atleaset give level 2 or level 3 or you can also check the changes then you can increase the level in pull request.
