### ISSUE TITLE
Add Dynamic Background Feature Based on Time for World Clock

### ISSUE THREAD

**Issue by RiyaBhurse** [param-code/counter-app#38]
Currently, the background of the world clock feature is a static, solid color. I propose adding a dynamic background that changes based on the time of day, which would improve user experience and make the interface more interactive.

Feature Request:
Change the background dynamically depending on the time:
Morning: A background representing the morning (e.g., sunrise, light colors).
Afternoon: A brighter or neutral background to reflect daylight.
Evening/Night: A darker background to represent nighttime (e.g., starry night, dark shades).
This will make the world clock feel more engaging by visually representing time transitions.

Benefits:
Enhance user experience through dynamic, real-time visuals.
Help users intuitively understand the time of day.
Provide a more interactive and visually appealing interface.

Could you please assign this issue to me and tag it with GSSoC and Hacktoberfest labels?
I am excited to contribute to this project!
![Screenshot from 2024-10-03 22-36-09](https://github.com/user-attachments/assets/4bdcb6a6-f4d0-4074-b1bc-2db870d54d69)

**Comment by param-code** [comment]
Yeah Sure.Do what you want.All the Best!!
