### ISSUE TITLE
ENHANCEMENT Replacing the Twitter logo to 'X'

### ISSUE THREAD

**Issue by ArthKulkarni93** [param-code/counter-app#44]
<img width="760" alt="Screenshot 2024-10-04 at 2 16 17 PM" src="https://github.com/user-attachments/assets/50bf0f40-8814-49f8-be3b-930c80830eeb">
Currently the old logo is featured on the website as contact us for Twitter
i will change the logo to 'X' making it up-to-date under GSSOC-ext.

**Comment by Shashank1618** [comment]
@param-code can you please assign this issue to me and also add the label hactoberfest and gssoc-ext

**Comment by param-code** [comment]
> @param-code can you please assign this issue to me and also add the label hactoberfest and gssoc-ext

Yes.

**Comment by hemant2807** [comment]
can i be assigned this task? i already have completed it in my code..

**Comment by ArthKulkarni93** [comment]
It's already done @hemant2807
