### ISSUE TITLE
World Clock is not clearly visible for Dark mode

### ISSUE THREAD

**Issue by Lonwwolf14** [param-code/counter-app#46]
The world clock in dark mode is hard to see because it's black, blending with the dark background. Adjust the clock's color to improve visibility.

![image](https://github.com/user-attachments/assets/f8a7c523-4a5b-483b-b07b-514e628c85f5)

![image](https://github.com/user-attachments/assets/dce60016-d456-418a-a9fa-e917e1857896)

**Comment by param-code** [comment]
Sure.Do what you want.

**Comment by ar1701** [comment]
I want to contribute on this, can you please assign it to me ?
