### ISSUE TITLE
Add Issues Template

### ISSUE THREAD

**Issue by kushwxha** [param-code/counter-app#48]
There is no issue template for this project that one should follow before creating a new issue.
Hey @param-code,
can you assign it to me? I would like to work on it.

**Comment by param-code** [comment]
> There is no issue template for this project that one should follow before creating a new issue. Hey @param-code, can you assign it to me? I would like to work on it.

Sure.

**Comment by kushwxha** [comment]
hey @param-code,  what you want to add in issue template like  issues, bugs and new feature.
these are three things i am thinking of adding. 
is it ok or you have some suggestions?

**Comment by kushwxha** [comment]
hey @param-code,
can you please check this pr??
