### ISSUE TITLE
Timer features

### ISSUE THREAD

**Issue by param-code** [param-code/counter-app#5]
try adding a button that will move a tab or page that have timer like features :-
- you can  start a timer
- input time
- add some preset timers and start it
- pause it and reset it
- also add some visual and sound effects if possible

**Comment by abishek1740P** [comment]
@param-code  assign me this issue . i'd like to work on this .

**Comment by param-code** [comment]
> @param-code assign me this issue . i'd like to work on this .

Here you go.All the Best!!
