### ISSUE TITLE
Footer timer and world clock is not taking to correct location

### ISSUE THREAD

**Issue by kushwxha** [param-code/counter-app#50]
hey @param-code,
Its showing like this
![image](https://github.com/user-attachments/assets/e7d40c04-93f3-4425-ae9f-2ca3bab54ceb)
can you assign it to me?

**Comment by Sehrishzarin** [comment]
nope, its working fine for me 
![Screenshot 2024-10-05 021445](https://github.com/user-attachments/assets/096decb1-4389-476e-982b-8855d73bbd9e)
![Screenshot 2024-10-05 021559](https://github.com/user-attachments/assets/01a9f4d9-ad53-40fe-a3eb-10bdeef88e82)

**Comment by kushwxha** [comment]
https://github.com/user-attachments/assets/9fe5cf1f-b165-43a5-9481-ac37c2afce64

hey @param-code,
i have attached the video of issue.
you can check
