### ISSUE TITLE
I'd like to add a backword time feature

### ISSUE THREAD

**Issue by Sehrishzarin** [param-code/counter-app#53]
I want to contribute and make a feature where you can open a timer that shows how much time is left before the day ends, it could be used as a occasion (new year or something like that) timer that shows how much time is left before another day begins.

@param-code let me know what you think

**Comment by param-code** [comment]
Sure.

**Comment by param-code** [comment]
> I want to contribute and make a feature where you can open a timer that shows how much time is left before the day ends, it could be used as a occasion (new year or something like that) timer that shows how much time is left before another day begins.
> 
> @param-code let me know what you think

All the Best!!

**Comment by Sehrishzarin** [comment]
it may take some time now, the whole code has been changed with the new theme
