### ISSUE TITLE
Adding pause and resume feature

### ISSUE THREAD

**Issue by saiprasanna56** [param-code/counter-app#59]
This feature introduces a pause and resume functionality for the clock, allowing users to temporarily halt the timer or stopwatch and then resume it without losing track of the elapsed time. This addition is particularly useful for applications where users may need to take breaks or attend to interruptions without needing to restart the clock.

**Comment by ArinNigam** [comment]
I would like to work on this issue

**Comment by param-code** [comment]
Well sorry to inform both of you but this feature is already there so i am closing this issue.
