### ISSUE TITLE
Improve the CSS of the navbar

### ISSUE THREAD

**Issue by manya1632** [param-code/counter-app#61]
While  changing the background and the adding particles.js the navbar too needs change. I would like to do them so that together they look good. 
 
Please assign me for the job !

**Comment by param-code** [comment]
> While changing the background and the adding particles.js the navbar too needs change. I would like to do them so that together they look good.
> 
> Please assign me for the job !

Sure.Do what you can.All the Best!!

**Comment by arduvey29** [comment]
@param-code I'd like to work on this issue, could you please assign it to me?"

**Comment by anchalchaturvedi08** [comment]
@param-code Could you please assign this task to me? I would like to work on this issue as well.

**Comment by param-code** [comment]
Sure Sure!!
