### ISSUE TITLE
Maintain Uniformity while Navigating 

### ISSUE THREAD

**Issue by ArinNigam** [param-code/counter-app#62]
Footer position can be fix while navigating to different sections 
- Counter 
- Timer
- World Clock

**Comment by ArinNigam** [comment]
Please assign me this issue my PR is ready to be merged

**Comment by param-code** [comment]
> Please assign me this issue my PR is ready to be merged

Okay

**Comment by arduvey29** [comment]
@param-code I'd like to work on this issue, could you please assign it to me?"
