### ISSUE TITLE
Fixing Vercel Production 

### ISSUE THREAD

**Issue by ArinNigam** [param-code/counter-app#65]
Actual Behaviour: Deployment not found for world-clock and timer
Expected Behaviour: It should work fine for both routes

**Comment by ArinNigam** [comment]
Kindly assign me this issue. The PR is done. 
I have tested the production by deploying on my fork and it works fine

**Comment by param-code** [comment]
> Kindly assign me this issue. The PR is done. I have tested the production by deploying on my fork and it works fine

Okay.

**Comment by arduvey29** [comment]
@param-code I'd like to work on this issue, could you please assign it to me?
