### ISSUE TITLE
Insert delete option for each Lap

### ISSUE THREAD

**Issue by Ankitha2130** [param-code/counter-app#7]
I will work on inserting the delete option to each lap that appears in the place as shown in the picture and clicking on it deletes the particular lap.
![image](https://github.com/user-attachments/assets/827a9cae-4ea1-494a-abaa-c52aa343e8cf)
Can you please assign this issue to me @param-code .

**Comment by param-code** [comment]
> I will work on inserting the delete option to each lap that appears in the place as shown in the picture and clicking on it deletes the particular lap. ![image](https://private-user-images.githubusercontent.com/149484435/372743492-827a9cae-4ea1-494a-abaa-c52aa343e8cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NTA1NzcsIm5iZiI6MTcyNzg1MDI3NywicGF0aCI6Ii8xNDk0ODQ0MzUvMzcyNzQzNDkyLTgyN2E5Y2FlLTRlYTEtNDk0YS1hYmFhLWM1MmFhMzQzZThjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMlQwNjI0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNjVjNmNmMjBjMTk3YjJkOTM5NmI5NTI1YjVmYTkzMTE2OGVmMmY5ZGU5NTIxZDdmNjI3N2NlYzhlODk5ODAxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.aemz2hCQEzDq_RUAg5T-7FCd06tCLks5JstXTwAC_xQ) Can you please assign this issue to me @param-code .

Sure.Move forward with your ideas.All the Best
