### ISSUE TITLE
See over there,the "Home","Timer","Clock" are not aligned correctly and enough spacing is required..Under that copyright,2024 the whole line has to get enough alignment to make it perfect

### ISSUE THREAD

**Issue by ark0078** [param-code/counter-app#70]
![Screenshot (187)](https://github.com/user-attachments/assets/464e1a7e-c0fa-4c5f-8c4d-31948360d6e6)

@param-code @sanjay-kv @17arindam @samyak-aditya @HarshitShukla-dev 
Please assign me this issue so that I can fix it and make it perfect

**Comment by param-code** [comment]
sure.

**Comment by ark0078** [comment]
I've created a CSS file as well as html for the correction of the issue #70 ..Kindly check those files and please merge it into your project.Hope this helps..The alignment as well as spacing problem is gone.
![Screenshot (191)](https://github.com/user-attachments/assets/efbc5a3d-9711-488f-9d63-7773c663b72a)

Kindly merge it @param-code ..Please!!

**Comment by ark0078** [comment]
See #74

**Comment by ark0078** [comment]
@param-code

**Comment by arduvey29** [comment]
@param-code I am ready to contribute in this, could you please assign it to me?
