### ISSUE TITLE
Allow users to rename lap titles (e.g., Lap 1, Lap 2)

### ISSUE THREAD

**Issue by ananyag309** [param-code/counter-app#71]
Currently, lap titles like "Lap 1", "Lap 2", etc., are fixed. Users should have the ability to rename these lap titles for better customization and clarity.

**Comment by param-code** [comment]
> Currently, lap titles like "Lap 1", "Lap 2", etc., are fixed. Users should have the ability to rename these lap titles for better customization and clarity.

Sure.
