### ISSUE TITLE
Not only Github - Instagram ,Twitter are also not link properly

### ISSUE THREAD

**Issue by VivekShahare04** [param-code/counter-app#75]
Please assign this issue to me. I'll make the necessary corrections and contribute to the project. Kindly tag me with GSSoC and Hacktoberfest. @param-code

**Comment by param-code** [comment]
> Please assign this issue to me. I'll make the necessary corrections and contribute to the project. Kindly tag me with GSSoC and Hacktoberfest. @param-code

okay.
