### ISSUE TITLE
feat: want to add a world clock feature 

### ISSUE THREAD

**Issue by 17arindam** [param-code/counter-app#8]
want to add a world clock feature to this website where it will show time of different regions of the world
@param-code can i work on this?

**Comment by param-code** [comment]
> want to add a world clock feature to this website where it will show time of different regions of the world @param-code can i work on this?

Ofcourse you can.I am assigning you this now you can work on your ideas.All the Best!!

**Comment by HarshitShukla-dev** [comment]
What is the need of a world clock in a counter app?

**Comment by param-code** [comment]
> What is the need of a world clock in a counter app?



> What is the need of a world clock in a counter app?

well there is no need but if if someone wants to add some extra features and as long as that features go way far of the concept of the app then i think letting someone work on the idea is kinda Good.
