### ISSUE TITLE
scrolling issue 

### ISSUE THREAD

**Issue by venurockss** [param-code/counter-app#81]
![Screenshot 2024-10-06 170814](https://github.com/user-attachments/assets/4fdd287b-533c-4156-9c94-88007ec6898f)
I noticed an issue with the Lap button on the site. When scrolling, the Lap button does not stay fixed and moves improperly, leading to a poor user experience. I've attached a screenshot highlighting the problem. I would like to take on this issue and work on a fix if you could kindly assign it to me.

**Comment by param-code** [comment]
> ![Screenshot 2024-10-06 170814](https://private-user-images.githubusercontent.com/146567450/373943304-4fdd287b-533c-4156-9c94-88007ec6898f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDQ3MTEsIm5iZiI6MTcyODcwNDQxMSwicGF0aCI6Ii8xNDY1Njc0NTAvMzczOTQzMzA0LTRmZGQyODdiLTUzM2MtNDE1Ni05Yzk0LTg4MDA3ZWM2ODk4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMzQwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjc1NjM3Mzg5MGQxYTk1OTVkZDYyNTY0ZGM0N2IwNTM5MDlhMGNjMjE0NjFmOWQzZTNjZmRmMTE1YmU3YmQ1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Y52HtZ5XvRwwNkc66A6ayRWbDTohCN7ZikOBZ-e3D2w) I noticed an issue with the Lap button on the site. When scrolling, the Lap button does not stay fixed and moves improperly, leading to a poor user experience. I've attached a screenshot highlighting the problem. I would like to take on this issue and work on a fix if you could kindly assign it to me.

Sure.
