### ISSUE TITLE
Improve Design of '404: Page Not Found' Error Page"

### ISSUE THREAD

**Issue by venurockss** [param-code/counter-app#82]
![Screenshot 2024-10-06 170709](https://github.com/user-attachments/assets/195775a8-38aa-4642-a57a-a742ad5214dd)
I noticed that when a user navigates to a random or non-existent URL, the "404: Page Not Found" page is not properly designed or visually appealing. The current layout could be enhanced to provide a better user experience. I've attached a screenshot for reference. I would be happy to work on redesigning this page if you could assign this issue to me.

**Comment by param-code** [comment]
> ![Screenshot 2024-10-06 170709](https://private-user-images.githubusercontent.com/146567450/373943789-195775a8-38aa-4642-a57a-a742ad5214dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDQ3MTAsIm5iZiI6MTcyODcwNDQxMCwicGF0aCI6Ii8xNDY1Njc0NTAvMzczOTQzNzg5LTE5NTc3NWE4LTM4YWEtNDY0Mi1hNTdhLWE3NDJhZDUyMTRkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMzQwMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yZDc4N2U1ODUxOWJkZjc2OTViZGIxMjQ0ZDhkMTRlOTY1NjFlMjk1NzVjZTVmNzc1YzgwZGUxNjIxM2NiMmU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TwBuJR457t8bOQKgNMXZaC4hUyWDZwdS6wcJwvPWGeM) I noticed that when a user navigates to a random or non-existent URL, the "404: Page Not Found" page is not properly designed or visually appealing. The current layout could be enhanced to provide a better user experience. I've attached a screenshot for reference. I would be happy to work on redesigning this page if you could assign this issue to me.

Okay.All the Best!!

**Comment by harshbhar0629** [comment]
Can i work on this issue?? Please @param-code, I will add 404 page for all pages which is not exist in this project.

**Comment by harshbhar0629** [comment]
Please i will make 404 page very intersting!

**Comment by harshbhar0629** [comment]
Improve Design of '404: Page Not Found' Error Page" #82 is not being resolved by last week will you please reassign this issue to me:)
