### ISSUE TITLE
Website Opens at the Bottom of the Page Upon Load

### ISSUE THREAD

**Issue by LitZeus** [param-code/counter-app#83]
When opening the website, the page automatically scrolls to the bottom instead of starting at the top. This behavior occurs consistently across all pages and affects the user experience. The expected behavior is for the page to open at the top by default. The issue can be observed in the attached video, which demonstrates the page automatically scrolling to the end upon load.

### Steps to reproduce:

1. Open the website.
2. Observe that the page scrolls to the bottom instead of remaining at the top.

### _Expected behavior_: The website should load at the top of the page by default, providing a better user experience.

https://github.com/user-attachments/assets/ee8130c0-093a-40f1-80d0-096d9a44b412

**Comment by param-code** [comment]
> When opening the website, the page automatically scrolls to the bottom instead of starting at the top. This behavior occurs consistently across all pages and affects the user experience. The expected behavior is for the page to open at the top by default. The issue can be observed in the attached video, which demonstrates the page automatically scrolling to the end upon load.
> 
> ### Steps to reproduce:
> 1. Open the website.
> 2. Observe that the page scrolls to the bottom instead of remaining at the top.
> 
> ### _Expected behavior_: The website should load at the top of the page by default, providing a better user experience.
>  Counter.App.and.2.more.pages.-.Personal.-.Microsoft.Edge.2024-10-06.18-11-24.mp4 
> ### I would like to work on the issue. Can you assign it to me under `gssoc-ext` and `hacktoberfest-accepted`

Sure.All the Best!!
