### ISSUE TITLE
adding Code of Conduct 

### ISSUE THREAD

**Issue by jyothimanoj12** [param-code/counter-app#87]
A Code of Conduct ensures inclusivity, prevents harassment, clarifies behavioral expectations, encourages professionalism, and fosters a safe, welcoming community for contributors.

plz assisn me this issue under gsoc-extended , level 1 , hacktoberfest-accepted tag

**Comment by param-code** [comment]
> A Code of Conduct ensures inclusivity, prevents harassment, clarifies behavioral expectations, encourages professionalism, and fosters a safe, welcoming community for contributors.
> 
> plz assisn me this issue under gsoc-extended , level 1 , hacktoberfest-accepted tag

Sure.

**Comment by jyothimanoj12** [comment]
#157
