### ISSUE TITLE
World Clock not found (Footer hyperlink)

### ISSUE THREAD

**Issue by Saaarthak0102** [param-code/counter-app#88]
![image](https://github.com/user-attachments/assets/c13d058d-177d-4168-b0e2-0a183a1afee8)
We cannot open World clock from the footer given below.

I would like to work on it!

**Comment by param-code** [comment]
> ![image](https://private-user-images.githubusercontent.com/174188123/374473589-c13d058d-177d-4168-b0e2-0a183a1afee8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDQ3MDEsIm5iZiI6MTcyODcwNDQwMSwicGF0aCI6Ii8xNzQxODgxMjMvMzc0NDczNTg5LWMxM2QwNThkLTE3N2QtNDE2OC1iMGUyLTBhMTgzYTFhZmVlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMzQwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MDgyYmFmYjU4YmRiMGQ5OGFkYzBjZGYwNDZhYjUyYTdhNTcxZmNkMWIxODRjMmVjMTU3MjBhZDY1YTI3ZDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3i07wq-FM_Lm-dZ05rmXGsQRm_XXWHnciDx_p_Nei9A) We cannot open World clock from the footer given below.
> 
> I would like to work on it!

okay.

**Comment by Saaarthak0102** [comment]
thank you for assigning!
will start working on this soon!

**Comment by Saaarthak0102** [comment]
pr merged!
