### ISSUE TITLE
adding storage features to the signup pages✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [param-code/counter-app#89]
the github link is broken and the navbar needs to be fixed as links are broken there.
when ur in the world clock u cant go back to counter , i can add that in the navbar.
i want to add a digital clock as well.

@param-code can you assign me this task.

<img width="1180" alt="Screenshot 2024-10-08 at 8 27 40 PM" src="https://github.com/user-attachments/assets/29dfd2f3-d14a-4f99-a89f-7b0148676422">
<img width="84" alt="Screenshot 2024-10-08 at 8 27 45 PM" src="https://github.com/user-attachments/assets/5bcf8382-ca3d-441e-972e-7c131abd4642">

**Comment by param-code** [comment]
> the github link is broken and the navbar needs to be fixed as links are broken there. when ur in the world clock u cant go back to counter , i can add that in the navbar. i want to add a digital clock as well.
> 
> @param-code can you assign me this task.
> 
> <img alt="Screenshot 2024-10-08 at 8 27 40 PM" width="1180" src="https://private-user-images.githubusercontent.com/167653990/374612668-29dfd2f3-d14a-4f99-a89f-7b0148676422.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDQ2OTksIm5iZiI6MTcyODcwNDM5OSwicGF0aCI6Ii8xNjc2NTM5OTAvMzc0NjEyNjY4LTI5ZGZkMmYzLWQxNGEtNGY5OS1hODlmLTdiMDE0ODY3NjQyMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMzM5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2Y4NTI4ZTJhMzcwNzkyMDBiODBmZTUyMDE4MWQyYmY3YjMzNjY1NDg1ZjMxMWJhMDc2NjY4MTI1ZTEyYWFkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qQRSBmUm-4QhZtZwvcrcwjCWCowBqluydnvQOd9hNdw"> <img alt="Screenshot 2024-10-08 at 8 27 45 PM" width="84" src="https://private-user-images.githubusercontent.com/167653990/374612676-5bcf8382-ca3d-441e-972e-7c131abd4642.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDQ2OTksIm5iZiI6MTcyODcwNDM5OSwicGF0aCI6Ii8xNjc2NTM5OTAvMzc0NjEyNjc2LTViY2Y4MzgyLWNhM2QtNDQxZS05NzJlLTdjMTMxYWJkNDY0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMzM5NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTI0MGI3MzIyMWNmNGJhZjk5NzA5M2E2YzRmMTY0YWNlMzJjZDMwYjdkOWM3NTg1ODIxZWVlNzNiNGI1NWQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2TaL8Lhply4FAb-e9-zBY4Z6bbQHVIZUZZG9QoRRLwE">

Ofcourse.All the Best.

**Comment by T-Rahul-prabhu-38** [comment]
<img width="581" alt="Screenshot 2024-10-12 at 9 28 07 AM" src="https://github.com/user-attachments/assets/96f02045-52ab-4825-953d-22154b7818e1">
the issue i wanted to fix has been solved.
can i instead add storage feature where u can signup and login and the user details will be saved in the local storage.
@param-code

**Comment by param-code** [comment]
> <img alt="Screenshot 2024-10-12 at 9 28 07 AM" width="581" src="https://private-user-images.githubusercontent.com/167653990/375921726-96f02045-52ab-4825-953d-22154b7818e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDU5MjEsIm5iZiI6MTcyODcwNTYyMSwicGF0aCI6Ii8xNjc2NTM5OTAvMzc1OTIxNzI2LTk2ZjAyMDQ1LTUyYWItNDgyNS05NTNkLTIyMTU0Yjc4MThlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNDAwMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGM0NzFhMzk4ODU2NzNjMWNiNGJhOTBjZjE5Mzc3M2U4NGE1ZmE0OTRiOTQxZGE5NDA5ZmFlZWY0ODRiZDJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1qD0ERXHgXFzZVDoVPqgVhSFZnm2qzLBLX55YT3Zoz0"> the issue i wanted to fix has been solved. can i instead add storage feature where u can signup and login and the user details will be saved in the local storage. @param-code

Okay.All the Best!!
