### ISSUE TITLE
Update README for Navigable Table of Contents

### ISSUE THREAD

**Issue by Pallavi-Mukalla** [param-code/counter-app#90]
I would like to enhance the README file by adding a navigable Table of Contents that links to specific sections. This will improve user experience by allowing easy access to different parts of the documentation. Ensure that all relevant headings have corresponding links in the Table of Contents.

@param-code please assign me this task

**Comment by param-code** [comment]
> I would like to enhance the README file by adding a navigable Table of Contents that links to specific sections. This will improve user experience by allowing easy access to different parts of the documentation. Ensure that all relevant headings have corresponding links in the Table of Contents.
> 
> @param-code please assign me this task

Sure.
