### ISSUE TITLE
Add admin user link in github icon in website

### ISSUE THREAD

**Issue by Aditijainnn** [param-code/counter-app#92]
![image](https://github.com/user-attachments/assets/9a5bcc00-bfde-4a8d-bf5e-b047401823a5)
in this icon adding your github profile link
assign this to me under gssoc ext

**Comment by param-code** [comment]
well this issue already got resolved but if you feel you can make other changes,feel free to do so.All the Best!!

**Comment by Aditijainnn** [comment]
> well this issue already got resolved but if you feel you can make other changes,feel free to do so.All the Best!!

can i enhance ui of signup page

**Comment by param-code** [comment]
> > well this issue already got resolved but if you feel you can make other changes,feel free to do so.All the Best!!
> 
> can i enhance ui of signup page

Sure.
