### ISSUE TITLE
Enhance ui of the footer section

### ISSUE THREAD

**Issue by T-Fathima** [param-code/counter-app#95]
## Enhancement Proposal

**Current Footer Design:**
- The current footer looks minimal and lacks interactivity.

**Proposed Enhancements:**
- Improve layout with better spacing and alignment.
- Make the footer responsive for mobile devices.
- Add better copyright text and navigation links.

**Benefits of the Enhancement:**
- Improves user experience.
- Provides quick access to important links.
- Increases website interactivity.

I would like to work on this issue.
@param-code Please assign this to me under gssoc-ext and hacktoberfest along with levels.
![image](https://github.com/user-attachments/assets/715bffb6-d66e-4d60-8b61-26bd653b6cce)

**Comment by param-code** [comment]
Okay.Make changes like you want.All the Best.
