### ISSUE TITLE
Create a new logo for the website Counter!

### ISSUE THREAD

**Issue by psa21git** [param-code/counter-app#96]
The white background is visible in the dark mode which looks very odd.
Also I would like to add a light color background for the world clock in dark mode. 
Also the world clock link in the footer is not working.
![image](https://github.com/user-attachments/assets/ed02956a-81d4-46e5-9530-81416e32119a)

**Comment by param-code** [comment]
Well some problems you mentioned are resolved already.Still see if you can do something.All the Best!!
