### ISSUE TITLE
Enhance Navigation Bar with Additional Sections (Home, About, Contact, etc.

### ISSUE THREAD

**Issue by aparna-44** [param-code/counter-app#97]
Currently, the Counter App's navigation bar lacks some key sections that could improve user experience.

Proposed Solution:
I suggest adding the following elements to the navigation bar:
1. **Home** - Link to the main page.
2. **About** - Explanation of the app's features and purpose.
3. **How It Works** - A section to guide new users.
4. **History** - Display past counter sessions (if applicable).
5. **Contact** - Feedback form or contact information.
6. **Themes** - Option to switch between light and dark modes.
7. **Login/Sign Up** - User authentication option (if relevant).
8. **Settings** - Access to app configurations.
@param-code plz assign me this issue

**Comment by param-code** [comment]
> Currently, the Counter App's navigation bar lacks some key sections that could improve user experience.
> 
> Proposed Solution: I suggest adding the following elements to the navigation bar:
> 
> 1. **Home** - Link to the main page.
> 2. **About** - Explanation of the app's features and purpose.
> 3. **How It Works** - A section to guide new users.
> 4. **History** - Display past counter sessions (if applicable).
> 5. **Contact** - Feedback form or contact information.
> 6. **Themes** - Option to switch between light and dark modes.
> 7. **Login/Sign Up** - User authentication option (if relevant).
> 8. **Settings** - Access to app configurations.
>    @param-code plz assign me this issue

Okay.Do what you can.I am assigning this to you.

**Comment by aparna-44** [comment]
yes I'm working on it
