### ISSUE TITLE
Improve Scroll Bar and Preloader

### ISSUE THREAD

**Issue by VidhanThakur09** [param-code/counter-app#98]
### Description
The current Scroll bar Ui has a very basic layout and outdated design and site Loading has no preloader. The screen becomes blank when the website loads. Enhancing the colour scheme of Thumb and Track, improving the preloader and modernizing the scroll bar design would greatly improve the user experience and website presentation

### Tasks:

- Redesign the Scroll bar and preloader for better visual appeal.
- Improving the scroll bar thump and track.
- Improving the preloader.

@param-code    can you assign this issue to me with labels "gssoc-ext" with levels ,"hacktoberfest-accepted";

### Add Screenshots or Sketches
**Without Preloader and without improvement in Scroll BAR**

![Screenshot 2024-10-11 192001](https://github.com/user-attachments/assets/2056534e-ec3d-43c4-a9e8-f087a15e7957)

![Screenshot 2024-10-11 191725](https://github.com/user-attachments/assets/3f20208c-a0b0-422e-bfe4-c1be1ac16a88)

###  Preloader Mockup
https://github.com/user-attachments/assets/eef3abe5-db44-4f17-abd0-292f63a89de9

**Comment by param-code** [comment]
Okay.Do the Best you can.I am assigning this to you.

**Comment by VidhanThakur09** [comment]
Thank you for assigning this to me . Could you please increase the level of this issue.
